<?php

declare(strict_types=1);

require_once __DIR__.'/GraphQLHelpers.php';
require_once __DIR__.'/AuthPlumbingTest.php';

use App\Models\Tax;
use Illuminate\Support\Str;
use App\Models\BillingEntity;
use App\Models\DunningCampaign;

/**
 * Ports of Rails' spec/graphql/mutations/taxes/*_spec.rb,
 * spec/graphql/mutations/billing_entities/{apply_taxes,remove_taxes,
 * update_applied_dunning_campaign}_spec.rb and the tax resolvers over the
 * frozen SDL.
 *
 * Ledger rows: gql:query:tax, gql:query:taxes, gql:mutation:createTax,
 * gql:mutation:updateTax, gql:mutation:destroyTax,
 * gql:query:billingEntityTaxes, gql:mutation:billingEntityApplyTaxes,
 * gql:mutation:billingEntityRemoveTaxes,
 * gql:mutation:billingEntityUpdateAppliedDunningCampaign.
 */
function gqlTaxesSetup(): array
{
    $organization = gqlCreateOrganization();
    $user = gqlCreateUser();

    gqlCreateMembership($user, $organization);

    return [$organization->refresh(), $user];
}

const CREATE_TAX_MUTATION = <<<'GQL'
mutation($input: TaxCreateInput!) {
    createTax(input: $input) {
        id code name description rate
        appliedToOrganization autoGenerated
    }
}
GQL;

const TAXES_QUERY = <<<'GQL'
query($page: Int, $limit: Int, $searchTerm: String, $order: String, $autoGenerated: Boolean, $appliedToOrganization: Boolean) {
    taxes(page: $page, limit: $limit, searchTerm: $searchTerm, order: $order, autoGenerated: $autoGenerated, appliedToOrganization: $appliedToOrganization) {
        collection { id code name rate }
        metadata { currentPage totalPages totalCount }
    }
}
GQL;

const TAX_QUERY = <<<'GQL'
query($id: ID!) {
    tax(id: $id) { id code name }
}
GQL;

const UPDATE_TAX_MUTATION = <<<'GQL'
mutation($input: TaxUpdateInput!) {
    updateTax(input: $input) { id code name rate }
}
GQL;

const DESTROY_TAX_MUTATION = <<<'GQL'
mutation($input: DestroyTaxInput!) {
    destroyTax(input: $input) { id }
}
GQL;

const BILLING_ENTITY_TAXES_QUERY = <<<'GQL'
query($billingEntityId: ID!) {
    billingEntityTaxes(billingEntityId: $billingEntityId) {
        collection { id code }
        metadata { totalCount }
    }
}
GQL;

const APPLY_TAXES_MUTATION = <<<'GQL'
mutation($input: ApplyTaxesInput!) {
    billingEntityApplyTaxes(input: $input) { appliedTaxes { id code } }
}
GQL;

const REMOVE_TAXES_MUTATION = <<<'GQL'
mutation($input: RemoveTaxesInput!) {
    billingEntityRemoveTaxes(input: $input) { removedTaxes { id code } }
}
GQL;

const UPDATE_APPLIED_DUNNING_CAMPAIGN_MUTATION = <<<'GQL'
mutation($input: BillingEntityUpdateAppliedDunningCampaignInput!) {
    billingEntityUpdateAppliedDunningCampaign(input: $input) {
        id appliedDunningCampaign { id }
    }
}
GQL;

it('creates a tax through createTax', function (): void {
    [$organization, $user] = gqlTaxesSetup();

    $payload = gqlPost(CREATE_TAX_MUTATION, ['input' => [
        'name' => 'VAT French standard',
        'code' => 'french_standard_vat',
        'rate' => 20,
        'description' => 'VAT French standard 20%',
    ]], gqlAuthHeaders($user, $organization->id))
        ->assertOk()->json('data.createTax');

    expect($payload['code'])->toBe('french_standard_vat')
        ->and($payload['name'])->toBe('VAT French standard')
        ->and($payload['rate'])->toEqual(20.0)
        ->and($payload['autoGenerated'])->toBeFalse();
});

it('answers validation errors from createTax with the error envelope', function (): void {
    [$organization, $user] = gqlTaxesSetup();

    $input = ['name' => 'TVA', 'code' => 'fr_standard_vat', 'rate' => 20];

    gqlPost(CREATE_TAX_MUTATION, ['input' => $input], gqlAuthHeaders($user, $organization->id))->assertOk();

    $response = gqlPost(CREATE_TAX_MUTATION, ['input' => $input], gqlAuthHeaders($user, $organization->id));

    expect($response->json('errors'))->not->toBeNull();
});

it('lists taxes through taxes with the search term and filters', function (): void {
    [$organization, $user] = gqlTaxesSetup();

    Tax::factory()->create(['organization_id' => $organization->id, 'name' => 'VAT', 'code' => 'vat', 'rate' => 20]);
    Tax::factory()->create(['organization_id' => $organization->id, 'name' => 'Auto tax', 'code' => 'auto_tax', 'rate' => 5, 'auto_generated' => true]);

    $payload = gqlPost(TAXES_QUERY, [], gqlAuthHeaders($user, $organization->id))
        ->assertOk()->json('data.taxes');

    expect(count($payload['collection']))->toBe(2);

    // Rails: ransack name/code OR — searching by code.
    $found = gqlPost(TAXES_QUERY, ['searchTerm' => 'vat'], gqlAuthHeaders($user, $organization->id))
        ->assertOk()->json('data.taxes');

    expect(count($found['collection']))->toBe(1)
        ->and($found['collection'][0]['code'])->toBe('vat');

    // Rails: with_auto_generated.
    $autoOnly = gqlPost(TAXES_QUERY, ['autoGenerated' => true], gqlAuthHeaders($user, $organization->id))
        ->assertOk()->json('data.taxes');

    expect(count($autoOnly['collection']))->toBe(1)
        ->and($autoOnly['collection'][0]['code'])->toBe('auto_tax');
});

it('fetches, updates and destroys a single tax', function (): void {
    [$organization, $user] = gqlTaxesSetup();

    $tax = Tax::factory()->create(['organization_id' => $organization->id]);

    expect(gqlPost(TAX_QUERY, ['id' => $tax->id], gqlAuthHeaders($user, $organization->id))
        ->assertOk()->json('data.tax.code'))->toBe($tax->code);

    // An unknown id answers the not_found error envelope.
    gqlPost(TAX_QUERY, ['id' => Str::uuid()], gqlAuthHeaders($user, $organization->id))
        ->assertOk()
        ->assertJsonPath('errors.0.extensions.code', 'not_found');

    expect(gqlPost(UPDATE_TAX_MUTATION, ['input' => [
        'id' => $tax->id,
        'name' => 'Renamed VAT',
        'code' => $tax->code,
        'rate' => 10,
    ]], gqlAuthHeaders($user, $organization->id))->assertOk()->json('data.updateTax.name'))->toBe('Renamed VAT');

    expect(gqlPost(DESTROY_TAX_MUTATION, ['input' => ['id' => $tax->id]], gqlAuthHeaders($user, $organization->id))
        ->assertOk()->json('data.destroyTax.id'))->toBe($tax->id);

    // A discarded tax no longer resolves.
    gqlPost(TAX_QUERY, ['id' => $tax->id], gqlAuthHeaders($user, $organization->id))
        ->assertOk()
        ->assertJsonPath('errors.0.extensions.code', 'not_found');
});

it('lists, applies and removes a billing entity taxes', function (): void {
    [$organization, $user] = gqlTaxesSetup();

    $billingEntity = BillingEntity::factory()->create(['organization_id' => $organization->id]);

    $tax = Tax::factory()->create(['organization_id' => $organization->id, 'code' => 'applied_vat']);

    // An unknown billing entity answers the not_found envelope.
    gqlPost(BILLING_ENTITY_TAXES_QUERY, ['billingEntityId' => Str::uuid()], gqlAuthHeaders($user, $organization->id))
        ->assertOk()
        ->assertJsonPath('errors.0.extensions.code', 'not_found');

    expect(count(gqlPost(BILLING_ENTITY_TAXES_QUERY, ['billingEntityId' => $billingEntity->id], gqlAuthHeaders($user, $organization->id))
        ->assertOk()->json('data.billingEntityTaxes.collection')))->toBe(0);

    $applied = gqlPost(APPLY_TAXES_MUTATION, ['input' => [
        'billingEntityId' => $billingEntity->id,
        'taxCodes' => ['applied_vat'],
    ]], gqlAuthHeaders($user, $organization->id))->assertOk()->json('data.billingEntityApplyTaxes.appliedTaxes');

    expect(count($applied))->toBe(1)->and($applied[0]['code'])->toBe('applied_vat');

    expect(count(gqlPost(BILLING_ENTITY_TAXES_QUERY, ['billingEntityId' => $billingEntity->id], gqlAuthHeaders($user, $organization->id))
        ->assertOk()->json('data.billingEntityTaxes.collection')))->toBe(1);

    $removed = gqlPost(REMOVE_TAXES_MUTATION, ['input' => [
        'billingEntityId' => $billingEntity->id,
        'taxCodes' => ['applied_vat'],
    ]], gqlAuthHeaders($user, $organization->id))->assertOk()->json('data.billingEntityRemoveTaxes.removedTaxes');

    expect(count($removed))->toBe(1)->and($removed[0]['code'])->toBe('applied_vat');
});

it('updates the applied dunning campaign of a billing entity', function (): void {
    [$organization, $user] = gqlTaxesSetup();

    $billingEntity = BillingEntity::factory()->create(['organization_id' => $organization->id]);

    $campaign = DunningCampaign::factory()->create(['organization_id' => $organization->id]);

    $payload = gqlPost(UPDATE_APPLIED_DUNNING_CAMPAIGN_MUTATION, ['input' => [
        'billingEntityId' => $billingEntity->id,
        'appliedDunningCampaignId' => $campaign->id,
    ]], gqlAuthHeaders($user, $organization->id))
        ->assertOk()->json('data.billingEntityUpdateAppliedDunningCampaign');

    expect($payload['appliedDunningCampaign']['id'])->toBe($campaign->id);

    // An unknown campaign answers the not_found envelope for dunning_campaign.
    gqlPost(UPDATE_APPLIED_DUNNING_CAMPAIGN_MUTATION, ['input' => [
        'billingEntityId' => $billingEntity->id,
        'appliedDunningCampaignId' => 'nope',
    ]], gqlAuthHeaders($user, $organization->id))
        ->assertOk()
        ->assertJsonPath('errors.0.extensions.code', 'not_found');
});
