#!/usr/bin/env php
<?php

declare(strict_types=1);

/**
 * Freeze the Rails schema for the Laravel port.
 *
 * Copies the Rails db/structure.sql (the schema source of truth — there is no
 * schema.rb) verbatim into database/frozen/, dropping only the documented
 * exclusion blocks. Anything else stays byte-identical so a later pg_dump
 * diff of the migrated database against the frozen file is clean.
 *
 * Usage: php scripts/freeze-schema.php <path-to-structure.sql>
 */
if ($argc < 2) {
    fwrite(STDERR, "Usage: php scripts/freeze-schema.php <path-to-structure.sql>\n");
    exit(1);
}

$src = $argv[1];
if (! is_file($src)) {
    fwrite(STDERR, "Source not found: {$src}\n");
    exit(1);
}

$destDir = __DIR__.'/../database/frozen';
if (! is_dir($destDir)) {
    mkdir($destDir, 0755, true);
}

// Exclusion patterns — each documented in EXCLUSIONS.md below. A pg_dump block
// (comment header or statement, blank-line separated) matching any pattern is
// dropped. Verified against structure.sql: no FK, sequence, or data block
// outside these objects references them.
$exclusions = [
    [
        'pattern' => '/\bpartman\b/',
        'reason' => 'pg_partman extension + partman schema (partition management is a runtime concern; re-enabled verbatim when events ingestion lands in M2)',
    ],
    [
        'pattern' => '/enriched_events/',
        'reason' => 'partitioned events table (public.enriched_events + default partition + its indexes/ATTACH blocks) — owned by the events path, M2+',
    ],
    [
        'pattern' => '/schema_migrations/',
        'reason' => 'Rails bookkeeping table + its INSERT data (Laravel has its own migrations table)',
    ],
    [
        'pattern' => '/ar_internal_metadata/',
        'reason' => 'Rails bookkeeping table',
    ],
    [
        'pattern' => "/set_config\\('search_path', '', false\\)/",
        'reason' => 'pg_dump replay preamble that blanks the session search_path — unsafe to leave set on a pooled Laravel connection; Laravel relies on the default public search_path and all frozen statements are schema-qualified anyway',
    ],
];

$raw = file_get_contents($src);

// pg_dump separates every header comment and every statement with a blank line.
$blocks = preg_split("/\n[ \t]*\n/", $raw);

$kept = [];
$dropped = [];
foreach ($blocks as $block) {
    $matched = null;
    foreach ($exclusions as $exclusion) {
        if (preg_match($exclusion['pattern'], $block) === 1) {
            $matched = $exclusion['reason'];
            break;
        }
    }
    if ($matched !== null) {
        $summary = mb_trim(preg_split('/\n/', $block)[0] ?? '');
        $dropped[] = [$summary, $matched];
    } else {
        $kept[] = $block;
    }
}

$out = implode("\n\n", $kept);
file_put_contents($destDir.'/structure.sql', $out);

// Auto-generated exclusion report — regenerated on every freeze run.
$lines = [
    '# Frozen schema exclusions',
    '',
    'Auto-generated by `scripts/freeze-schema.php` from the Rails `db/structure.sql`.',
    'Source: `'.basename($src).'`. Do not edit by hand — rerun the script.',
    '',
    'Excluded pg_dump blocks:',
    '',
];
$lastReason = null;
foreach ($dropped as [$summary, $reason]) {
    if ($reason !== $lastReason) {
        $lines[] = '';
        $lines[] = '- **'.$reason.'**';
        $lastReason = $reason;
    }
    $lines[] = '  - `'.$summary.'`';
}
$lines[] = '';
file_put_contents($destDir.'/EXCLUSIONS.md', implode("\n", $lines));

printf(
    "Froze %s -> %s (%d bytes kept, %d blocks dropped, %d blocks total)\n",
    $src,
    $destDir.'/structure.sql',
    mb_strlen($out),
    count($dropped),
    count($blocks)
);
