#!/usr/bin/env php
<?php

declare(strict_types=1);

/**
 * Generates Eloquent model skeletons for the frozen Lago schema, reading
 * column metadata from the live (migrated) database. Output is a starting
 * point: models are hand-refined as their services are ported, but casts and
 * column names come from the schema, so they cannot drift from it.
 *
 * Usage: php scripts/gen-models.php "ClassName:table_name" [...] [--force]
 */
$pdo = new PDO(
    sprintf('pgsql:host=%s;port=%s;dbname=%s', getenv('DB_HOST') ?: '127.0.0.1', getenv('DB_PORT') ?: '5433', getenv('DB_DATABASE') ?: 'lago'),
    getenv('DB_USERNAME') ?: 'postgres',
    getenv('DB_PASSWORD') ?: 'postgres',
    [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION],
);

$args = array_slice($argv, 1);
$force = in_array('--force', $args, true);
$targets = array_filter($args, fn ($a) => $a !== '--force');

if (! $targets) {
    fwrite(STDERR, "Usage: php scripts/gen-models.php \"ClassName:table_name\" [...] [--force]\n");
    exit(1);
}

$castFor = (fn(array $col): ?string => match (true) {
    $col['data_type'] === 'ARRAY' => "'array'",
    $col['data_type'] === 'jsonb', $col['data_type'] === 'json' => "'array'",
    $col['data_type'] === 'boolean' => "'boolean'",
    in_array($col['data_type'], ['integer', 'smallint', 'bigint'], true) => "'integer'",
    $col['data_type'] === 'numeric' => sprintf("[BcNumeric::class, 'scale' => %d]", max(0, (int) $col['numeric_scale'])),
    str_starts_with($col['data_type'], 'timestamp') => "'datetime'",
    $col['data_type'] === 'date' => "'date:Y-m-d'",
    $col['data_type'] === 'double precision' => "'float'",
    default => null,
});

foreach ($targets as $target) {
    [$class, $table] = explode(':', $target, 2);

    $out = __DIR__.'/../app/Models/'.$class.'.php';
    if (file_exists($out) && ! $force) {
        printf("skip (exists): %s\n", $class);

        continue;
    }

    $stmt = $pdo->prepare(
        'SELECT column_name, data_type, udt_name, column_default, numeric_scale, is_nullable
         FROM information_schema.columns WHERE table_schema = \'public\' AND table_name = ?
         ORDER BY ordinal_position'
    );
    $stmt->execute([$table]);
    $columns = $stmt->fetchAll(PDO::FETCH_ASSOC);

    if (! $columns) {
        fwrite(STDERR, "table not found: {$table}\n");
        exit(1);
    }

    $fillable = [];
    $casts = [];
    $hasSoftDeletes = false;
    $hasTimestamps = false;
    foreach ($columns as $col) {
        $name = $col['column_name'];
        if ($name === 'id') {
            continue;
        }
        if ($name === 'deleted_at') {
            $hasSoftDeletes = true;

            continue;
        }
        if ($name === 'created_at' || $name === 'updated_at') {
            $hasTimestamps = true;

            continue;
        }
        $fillable[] = "'".$name."'";
        if ($cast = $castFor($col)) {
            if (str_starts_with($cast, 'BcNumeric')) {
                $casts[] = sprintf("        '%s' => %s,", $name, $cast);
            } else {
                $casts[] = sprintf("        '%s' => %s,", $name, $cast);
            }
        }
    }

    $ns = "App\Models".(str_contains($class, '\\') ? '\\'.str_replace('\\', '/', mb_substr($class, 0, mb_strpos($class, '\\') ?: 0)) : '');

    $php = '<?php

namespace App\\Models;

use App\\Models\\BaseModel;
'.($casts ? "use App\\Models\\Casts\\BcNumeric;\n" : '').($hasSoftDeletes ? "use Illuminate\\Database\\Eloquent\\SoftDeletes;\n" : '').'
/**
 * Frozen-schema model for `'.$table.'`. Generated by scripts/gen-models.php;
 * refine relations, enums and domain methods as services are ported.
 */
class '.(class_basename($class)).' extends BaseModel
{
'.($hasSoftDeletes ? "    use SoftDeletes;\n\n" : '').'    protected $table = \''.$table."';

    protected \$fillable = [
".implode("\n", array_map(fn ($f) => '        '.$f.',', $fillable)).'
    ];

    protected $casts = [
'.implode("\n", $casts).'
    ];
}
';

    file_put_contents($out, $php);
    printf("generated: %s (%d columns, softDeletes=%s)\n", $class, count($columns), $hasSoftDeletes ? 'yes' : 'no');
}

function class_basename(string $class): string
{
    $parts = explode('\\', $class);

    return end($parts);
}
