<?php

declare(strict_types=1);

namespace App\GraphQL\Queries;

use App\Queries\TaxesQuery;
use App\GraphQL\Support\Page;
use App\GraphQL\Execution\Errors;
use App\GraphQL\Support\LagoContext;
use App\GraphQL\Guards\AuthenticableApiUser;
use App\GraphQL\Guards\RequiredOrganization;
use Nuwave\Lighthouse\Support\Contracts\GraphQLContext;

/**
 * Port of Rails' Resolvers::TaxesResolver (app/graphql/resolvers/taxes_resolver.rb):
 * "Query taxes of an organization" — the search term, order and the
 * auto_generated / applied_to_organization filters go through the TaxesQuery
 * port, wrapped in the frozen SDL's TaxCollection shape.
 */
class Taxes
{
    public function __invoke(mixed $root, array $args, GraphQLContext $context): Page
    {
        AuthenticableApiUser::authorize($context);
        RequiredOrganization::authorize($context);

        $organization = LagoContext::currentOrganization($context);

        $result = TaxesQuery::call(
            organization: $organization,
            searchTerm: $args['searchTerm'] ?? null,
            pagination: [
                'page' => $args['page'] ?? null,
                'limit' => $args['limit'] ?? null,
            ],
            filters: [
                'auto_generated' => $args['autoGenerated'] ?? null,
                'applied_to_organization' => $args['appliedToOrganization'] ?? null,
            ],
            order: $args['order'] ?? null,
        );

        if ($result->failure()) {
            throw Errors::resultError($result->getError());
        }

        return Page::fromLengthAwarePaginator($result->taxes);
    }
}
