<?php

namespace App\Models;

use App\Models\BaseModel;
use App\Models\Casts\BcNumeric;

/**
 * Frozen-schema model for `api_keys`. Generated by scripts/gen-models.php;
 * refine relations, enums and domain methods as services are ported.
 */
class ApiKey extends BaseModel
{
    protected $table = 'api_keys';

    protected $fillable = [
        'organization_id',
        'value',
        'expires_at',
        'last_used_at',
        'name',
        'permissions',
    ];

    protected $casts = [
        'expires_at' => 'datetime',
        'last_used_at' => 'datetime',
        'permissions' => 'array',
    ];
}
