<?php

namespace App\Models;

use App\Models\BaseModel;
use App\Models\Casts\BcNumeric;

/**
 * Frozen-schema model for `applied_coupons`. Generated by scripts/gen-models.php;
 * refine relations, enums and domain methods as services are ported.
 */
class AppliedCoupon extends BaseModel
{
    protected $table = 'applied_coupons';

    protected $fillable = [
        'coupon_id',
        'customer_id',
        'status',
        'amount_cents',
        'amount_currency',
        'terminated_at',
        'percentage_rate',
        'frequency',
        'frequency_duration',
        'frequency_duration_remaining',
        'organization_id',
    ];

    protected $casts = [
        'status' => 'integer',
        'amount_cents' => 'integer',
        'terminated_at' => 'datetime',
        'percentage_rate' => [BcNumeric::class, 'scale' => 5],
        'frequency' => 'integer',
        'frequency_duration' => 'integer',
        'frequency_duration_remaining' => 'integer',
    ];
}
