<?php

declare(strict_types=1);

namespace App\Models;

use App\Models\Casts\BcNumeric;

/**
 * Frozen-schema model for `applied_coupons`. Generated by scripts/gen-models.php;
 * refine relations, enums and domain methods as services are ported.
 */
#[\Illuminate\Database\Eloquent\Attributes\Fillable([
    'coupon_id',
    'customer_id',
    'status',
    'amount_cents',
    'amount_currency',
    'terminated_at',
    'percentage_rate',
    'frequency',
    'frequency_duration',
    'frequency_duration_remaining',
    'organization_id',
])]
#[\Illuminate\Database\Eloquent\Attributes\Table(name: 'applied_coupons')]
class AppliedCoupon extends BaseModel
{
    protected function casts(): array
    {
        return [
            'status' => 'integer',
            'amount_cents' => 'integer',
            'terminated_at' => 'datetime',
            'percentage_rate' => [BcNumeric::class, 'scale' => 5],
            'frequency' => 'integer',
            'frequency_duration' => 'integer',
            'frequency_duration_remaining' => 'integer',
        ];
    }
}
