<?php

declare(strict_types=1);

namespace App\Models;

use App\Expression\Parser;
use App\Enums\AggregationType;
use App\Enums\RoundingFunction;
use App\Enums\WeightedInterval;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Models\Concerns\BelongsToOrganization;
use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Attributes\Table;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

/**
 * Frozen-schema model for `billable_metrics`. Generated by scripts/gen-models.php;
 * refined with the Rails BillableMetric model's enums, domain methods and
 * validations.
 */
#[Fillable([
    'organization_id',
    'name',
    'code',
    'description',
    'properties',
    'aggregation_type',
    'field_name',
    'recurring',
    'weighted_interval',
    'custom_aggregator',
    'expression',
    'rounding_function',
    'rounding_precision',
])]
#[Table(name: 'billable_metrics')]
class BillableMetric extends BaseModel
{
    use BelongsToOrganization;
    use HasFactory;
    use SoftDeletes;

    /** Rails: AGGREGATION_TYPES (integer enum; 4 deleted — never renumber). */
    public const AGGREGATION_TYPES = [
        'count_agg' => 0,
        'sum_agg' => 1,
        'max_agg' => 2,
        'unique_count_agg' => 3,
        // NOTE: deleted aggregation type, recurring_count_agg: 4,
        'weighted_sum_agg' => 5,
        'latest_agg' => 6,
        'custom_agg' => 7,
    ];

    /** Rails: AGGREGATION_TYPES_PAYABLE_IN_ADVANCE. */
    public const AGGREGATION_TYPES_PAYABLE_IN_ADVANCE = ['count_agg', 'sum_agg', 'unique_count_agg', 'custom_agg'];

    /** Rails: ROUNDING_FUNCTIONS. */
    public const ROUNDING_FUNCTIONS = ['round' => 'round', 'ceil' => 'ceil', 'floor' => 'floor'];

    /** Rails: WEIGHTED_INTERVAL. */
    public const WEIGHTED_INTERVAL = ['seconds' => 'seconds'];

    /**
     * Rails' ActiveRecord carries the schema's column defaults in every new
     * instance; Eloquent does not, so the NOT NULL DEFAULT columns are
     * declared here to keep reads (and the serializers) identical to Rails.
     */
    protected $attributes = [
        'properties' => '{}',
        'recurring' => false,
    ];

    // -- Attribute behavior ---------------------------------------------------

    /**
     * Rails enum assignments with unknown names (Rails' enum setters raise
     * ArgumentError; we record them here and the inclusion validations report
     * value_is_invalid instead).
     *
     * @var array<string, true>
     */
    protected array $invalidEnumAssignments = [];

    // -- Relationships --------------------------------------------------------

    /** Rails: `has_many :charges, dependent: :destroy`. */
    public function charges(): HasMany
    {
        return $this->hasMany(Charge::class);
    }

    /** Rails: `has_many :filters, -> { order(:key) }, dependent: :delete_all, class_name: "BillableMetricFilter"`. */
    /**
     * Rails: `has_many :product_filter_values, through: :filters`
     * (usage-monitoring slice, appended) — kept as an explicit whereIn over
     * the kept filters so the intermediate default scope (discard) applies
     * exactly like Rails' through.
     */
    public function productFilterValues()
    {
        return ProductFilterValue::query()
            ->whereIn('billable_metric_filter_id', $this->filters()->select('id'));
    }

    public function filters(): HasMany
    {
        return $this->hasMany(BillableMetricFilter::class);
    }

    /** Rails: `has_many :plans, through: :charges`. */
    public function plans(): BelongsToMany
    {
        return $this->belongsToMany(Plan::class, 'charges', 'billable_metric_id', 'plan_id')
            ->whereNull('charges.deleted_at');
    }

    // -- Domain methods (ports of the Rails instance methods) ------------------

    /** Rails: `payable_in_advance?`. */
    public function payableInAdvance(): bool
    {
        $type = $this->rawAggregationType();

        return $type !== null && in_array(
            AggregationType::from((int) $type)->label(),
            self::AGGREGATION_TYPES_PAYABLE_IN_ADVANCE,
            true,
        );
    }

    /**
     * Rails: `attached_to_plan?` — replaces `billable_metric.plans.exists?`
     * to force the planner onto index_charges_on_billable_metric_id.
     */
    public function attachedToPlan(): bool
    {
        return Charge::query()
            ->where('billable_metric_id', $this->id)
            ->whereRaw('EXISTS (SELECT 1 FROM plans WHERE plans.id = charges.plan_id AND plans.deleted_at IS NULL)')
            ->exists();
    }

    /**
     * Rails: `attached_subscriptions` — subscriptions of the plans that carry
     * a (kept) charge for this metric.
     */
    public function attachedSubscriptions(): Builder
    {
        return Subscription::query()
            ->whereIn('plan_id', $this->charges()->select('charges.plan_id'))
            ->where('organization_id', $this->organization_id);
    }

    // -- Validations ------------------------------------------------------------

    /**
     * Port of the Rails model validations (including the
     * before_validation :reset_field_name_for_count_agg callback) —
     * `field => [api error codes]`, empty when valid.
     *
     * @return array<string, list<string>>
     */
    public function validateAttributes(): array
    {
        // Rails: before_validation :reset_field_name_for_count_agg — count_agg
        // does not aggregate on a property, so a field_name coming from a
        // previous aggregation type must be dropped rather than persisted.
        if ($this->countAgg()) {
            $this->field_name = null;
        }

        $errors = [];

        if (($this->name ?? '') === '') {
            $errors['name'] = ['value_is_mandatory'];
        }

        if ($this->shouldHaveFieldName() && ($this->field_name ?? '') === '') {
            $errors['field_name'] = ['value_is_mandatory'];
        }

        $aggregationType = $this->rawAggregationType();

        if ($aggregationType === null || AggregationType::tryFrom((int) $aggregationType) === null) {
            $errors['aggregation_type'] = ['value_is_invalid'];
        }

        if (($this->code ?? '') === '') {
            $errors['code'] = ['value_is_mandatory'];
        } else {
            $uniqueness = static::query()
                ->where('code', $this->code)
                ->where('organization_id', $this->organization_id)
                ->whereNull('deleted_at');

            if ($this->exists) {
                $uniqueness->where($this->getKeyName(), '!=', $this->getKey());
            }

            if ($uniqueness->exists()) {
                $errors['code'] = ['value_already_exist'];
            }
        }

        if ($this->weightedSumAgg() && ! in_array($this->raw('weighted_interval'), self::WEIGHTED_INTERVAL, true)) {
            $errors['weighted_interval'] = ['value_is_invalid'];
        } elseif (isset($this->invalidEnumAssignments['weighted_interval'])) {
            $errors['weighted_interval'] = ['value_is_invalid'];
        }

        if ($this->customAgg() && ($this->custom_aggregator ?? '') === '') {
            $errors['custom_aggregator'] = ['value_is_mandatory'];
        }

        $roundingFunction = $this->raw('rounding_function');

        if (($roundingFunction !== null && ! in_array($roundingFunction, self::ROUNDING_FUNCTIONS, true))
            || isset($this->invalidEnumAssignments['rounding_function'])) {
            $errors['rounding_function'] = ['value_is_invalid'];
        }

        $this->validateRecurring($errors);
        $this->validateExpression($errors);

        return $errors;
    }

    /** Rails: `count_agg?`. */
    public function countAgg(): bool
    {
        return (int) $this->rawAggregationType() === AggregationType::CountAgg->value;
    }

    /** Rails: `sum_agg?`. */
    public function sumAgg(): bool
    {
        return (int) $this->rawAggregationType() === AggregationType::SumAgg->value;
    }

    /** Rails: `max_agg?`. */
    public function maxAgg(): bool
    {
        return (int) $this->rawAggregationType() === AggregationType::MaxAgg->value;
    }

    /** Rails: `unique_count_agg?`. */
    public function uniqueCountAgg(): bool
    {
        return (int) $this->rawAggregationType() === AggregationType::UniqueCountAgg->value;
    }

    /** Rails: `weighted_sum_agg?`. */
    public function weightedSumAgg(): bool
    {
        return (int) $this->rawAggregationType() === AggregationType::WeightedSumAgg->value;
    }

    /** Rails: `latest_agg?`. */
    public function latestAgg(): bool
    {
        return (int) $this->rawAggregationType() === AggregationType::LatestAgg->value;
    }

    /** Rails: `custom_agg?`. */
    public function customAgg(): bool
    {
        return (int) $this->rawAggregationType() === AggregationType::CustomAgg->value;
    }

    protected function casts(): array
    {
        return [
            'properties' => 'array',
            'aggregation_type' => AggregationType::class,
            'recurring' => 'boolean',
            'weighted_interval' => WeightedInterval::class,
            'rounding_function' => RoundingFunction::class,
            'rounding_precision' => 'integer',
        ];
    }

    /**
     * Rails: `def aggregation_type=(value)` — assigns the enum position when
     * the Rails enum NAME is known, silently keeps the previous value
     * otherwise (invalid input surfaces through the inclusion validation as
     * value_is_invalid).
     */
    protected function aggregationType(): Attribute
    {
        return Attribute::set(function (mixed $value) {
            $mapped = AggregationType::fromOption($value)?->value;

            return $mapped ?? $this->getAttributes()['aggregation_type'] ?? null;
        });
    }

    /**
     * Rails: `enum :rounding_function` — an unknown name would raise; we null
     * it (allow_nil) and record the assignment for the inclusion validation.
     */
    protected function roundingFunction(): Attribute
    {
        return Attribute::set(function (mixed $value) {
            $mapped = RoundingFunction::fromOption($value)?->value;

            if ($mapped === null && $value !== null) {
                $this->invalidEnumAssignments['rounding_function'] = true;
            }

            return $mapped;
        });
    }

    /** Same handling as rounding_function for the weighted_interval PG enum. */
    protected function weightedInterval(): Attribute
    {
        return Attribute::set(function (mixed $value) {
            $mapped = WeightedInterval::fromOption($value)?->value;

            if ($mapped === null && $value !== null) {
                $this->invalidEnumAssignments['weighted_interval'] = true;
            }

            return $mapped;
        });
    }

    /** The raw (unmapped) aggregation_type column value — the enum position. */
    protected function rawAggregationType(): int|string|null
    {
        return $this->raw('aggregation_type');
    }

    /**
     * The raw column value — the attribute mutators store the DB
     * representation (enum position / PG enum label), for new and loaded
     * records alike, so validations read through it in both cases.
     */
    protected function raw(string $key): mixed
    {
        return $this->getAttributes()[$key] ?? null;
    }

    /** Rails: `should_have_field_name?` — every aggregation but count and custom. */
    protected function shouldHaveFieldName(): bool
    {
        return ! $this->countAgg() && ! $this->customAgg();
    }

    /** Rails: `validate_recurring` — recurring is incompatible with count/max/latest. */
    protected function validateRecurring(array &$errors): void
    {
        if ($this->recurring !== true) {
            return;
        }

        if ($this->countAgg() || $this->maxAgg() || $this->latestAgg()) {
            $errors['recurring'] = ['not_compatible_with_aggregation_type'];
        }
    }

    /**
     * Rails: `validate_expression` — Lago::ExpressionParser.validate returns
     * the parse errors; blank expressions always pass.
     */
    protected function validateExpression(array &$errors): void
    {
        $expression = $this->expression;

        if ($expression === null || mb_trim((string) $expression) === '') {
            return;
        }

        if (Parser::validate((string) $expression) !== null) {
            $errors['expression'] = ['invalid_expression'];
        }
    }
}
