<?php

declare(strict_types=1);

namespace App\Models;

use App\Models\Casts\PostgresArray;
use App\Enums\EntityDocumentNumbering;
use App\Services\Validators\Countries;
use App\Services\Validators\Timezones;
use App\Services\Validators\Currencies;
use App\Services\Validators\EuVatRates;
use Illuminate\Database\Eloquent\Builder;
use App\Services\Validators\EmailSanitizer;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Attributes\Scope;
use Illuminate\Database\Eloquent\Attributes\Table;
use App\Enums\SubscriptionInvoiceIssuingDateAnchor;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use App\Enums\SubscriptionInvoiceIssuingDateAdjustment;

/**
 * Frozen-schema model for `billing_entities`. Generated by scripts/gen-models.php;
 * refined with the Rails BillingEntity model's relations, enums, scopes and
 * validations.
 */
#[Fillable([
    'organization_id',
    'address_line1',
    'address_line2',
    'city',
    'country',
    'zipcode',
    'state',
    'timezone',
    'default_currency',
    'document_locale',
    'document_number_prefix',
    'document_numbering',
    'finalize_zero_amount_invoice',
    'invoice_footer',
    'invoice_grace_period',
    'net_payment_term',
    'email',
    'email_settings',
    'eu_tax_management',
    'legal_name',
    'legal_number',
    'logo',
    'name',
    'code',
    'tax_identification_number',
    'vat_rate',
    'archived_at',
    'applied_dunning_campaign_id',
    'einvoicing',
    'subscription_invoice_issuing_date_anchor',
    'subscription_invoice_issuing_date_adjustment',
    'phone',
    'payment_term',
])]
#[Table(name: 'billing_entities')]
class BillingEntity extends BaseModel
{
    use HasFactory;
    use SoftDeletes;

    public const EMAIL_SETTINGS = [
        'invoice.finalized',
        'credit_note.created',
        'payment_receipt.created',
    ];

    /** Rails: EINVOICING_COUNTRIES. */
    public const EINVOICING_COUNTRIES = ['FR', 'DE'];

    /** Rails' I18n.available_locales (LanguageCodeValidator data). */
    public const AVAILABLE_LOCALES = ['en', 'fr', 'nb', 'de', 'it', 'es', 'sv', 'pt-BR', 'zh-TW'];

    /**
     * Rails' ActiveRecord carries the schema's column defaults in every new
     * instance; Eloquent does not, so they are declared here.
     */
    protected $attributes = [
        'timezone' => 'UTC',
        'default_currency' => 'USD',
        'document_locale' => 'en',
        'document_numbering' => 'per_customer',
        'finalize_zero_amount_invoice' => true,
        'invoice_grace_period' => 0,
        'net_payment_term' => 0,
        'email_settings' => '{}',
        'eu_tax_management' => false,
        'einvoicing' => false,
        'vat_rate' => 0.0,
        'subscription_invoice_issuing_date_anchor' => 'next_period_start',
        'subscription_invoice_issuing_date_adjustment' => 'align_with_finalization_date',
    ];

    /**
     * Rails: `update!(document_number_prefix: "#{name.first(3).upcase}-#{id.last(4).upcase}")
     * if document_number_prefix.nil?`
     */
    public function generateDocumentNumberPrefix(): void
    {
        if ($this->document_number_prefix !== null) {
            return;
        }

        $this->forceFill([
            'document_number_prefix' => mb_strtoupper(mb_substr($this->name, 0, 3)).'-'.mb_strtoupper(mb_substr($this->id, -4)),
        ])->save();
    }

    /** Port of BillingEntity#eu_vat_eligible?. */
    public function euVatEligible(): bool
    {
        return $this->country !== null
            && in_array($this->country, EuVatRates::countryCodes(), true);
    }

    /** Port of BillingEntity#eligible_for_einvoicing?. */
    public function eligibleForEinvoicing(): bool
    {
        return $this->einvoicing && in_array(mb_strtoupper((string) $this->country), self::EINVOICING_COUNTRIES, true);
    }

    // -- Relationships --------------------------------------------------------

    public function organization(): BelongsTo
    {
        return $this->belongsTo(Organization::class);
    }

    public function customers(): HasMany
    {
        return $this->hasMany(Customer::class);
    }

    // -- Validations ----------------------------------------------------------

    /**
     * Port of the Rails model validations — `field => [api error codes]`,
     * empty when valid.
     *
     * @return array<string, list<string>>
     */
    public function validateAttributes(): array
    {
        $errors = [];

        $codeErrors = [];
        if (($this->code ?? '') === '') {
            $codeErrors[] = 'value_is_mandatory';
        } else {
            $uniqueness = static::query()
                ->where('code', $this->code)
                ->where('organization_id', $this->organization_id)
                ->whereNull('archived_at')
                ->whereNull('deleted_at');

            if ($this->exists) {
                $uniqueness->where($this->getKeyName(), '!=', $this->getKey());
            }

            if ($uniqueness->exists()) {
                $codeErrors[] = 'value_already_exist';
            }
        }

        if ($codeErrors !== []) {
            $errors['code'] = $codeErrors;
        }

        if ($this->country !== null && ! Countries::valid($this->country)) {
            $errors['country'] = ['not_a_valid_country_code'];
        }

        if (! Currencies::valid($this->getRawOriginal('default_currency'))) {
            $errors['default_currency'] = ['value_is_invalid'];
        }

        if ($this->document_locale !== null && ! in_array($this->document_locale, self::AVAILABLE_LOCALES, true)) {
            $errors['document_locale'] = ['not_a_valid_language_code'];
        }

        if ($this->email !== null && $this->email !== '' && ! EmailSanitizer::valid($this->email)) {
            $errors['email'] = ['invalid_email_format'];
        }

        if ($this->invoice_footer !== null && mb_strlen($this->invoice_footer) > 600) {
            $errors['invoice_footer'] = ['value_is_too_long'];
        }

        if ($this->document_number_prefix !== null
            && (mb_strlen($this->document_number_prefix) < 1 || mb_strlen($this->document_number_prefix) > 10)) {
            $errors['document_number_prefix'] = [mb_strlen($this->document_number_prefix) > 10 ? 'value_is_too_long' : 'value_is_too_short'];
        }

        foreach (['invoice_grace_period' => $this->invoice_grace_period, 'net_payment_term' => $this->net_payment_term] as $field => $value) {
            if ($value !== null && $value < 0) {
                $errors[$field] = ['value_is_out_of_range'];
            }
        }

        if (($this->name ?? '') === '') {
            $errors['name'] = ['value_is_mandatory'];
        }

        if ($this->getRawOriginal('timezone') !== null && ! Timezones::valid($this->getRawOriginal('timezone'))) {
            $errors['timezone'] = ['invalid_timezone'];
        }

        foreach ((array) ($this->email_settings ?? []) as $setting) {
            if (! in_array($setting, self::EMAIL_SETTINGS, true)) {
                $errors['email_settings'] = ['unsupported_value'];

                break;
            }
        }

        return $errors;
    }

    // -- Lifecycle ------------------------------------------------------------

    protected static function booted(): void
    {
        // Rails: after_create :generate_document_number_prefix
        static::created(function (self $entity): void {
            $entity->generateDocumentNumberPrefix();
        });
    }

    // -- Scopes --------------------------------------------------------------

    /** Rails: `scope :active, -> { where(archived_at: nil).order(created_at: :asc) }`. */
    #[Scope]
    protected function active(Builder $query): Builder
    {
        return $query->whereNull('archived_at')->oldest('created_at');
    }

    // -- Attribute behavior ---------------------------------------------------

    protected function email(): Attribute
    {
        return Attribute::set(
            fn (?string $value) => EmailSanitizer::sanitize($value),
        );
    }

    /** Rails: `def country=(value); super(value&.upcase); end` */
    protected function country(): Attribute
    {
        return Attribute::set(
            fn (?string $value) => $value === null ? null : mb_strtoupper($value),
        );
    }

    /** Rails: `def document_number_prefix=(value); super(value&.upcase); end` */
    protected function documentNumberPrefix(): Attribute
    {
        return Attribute::set(
            fn (?string $value) => $value === null ? null : mb_strtoupper($value),
        );
    }

    protected function casts(): array
    {
        return [
            'finalize_zero_amount_invoice' => 'boolean',
            'invoice_grace_period' => 'integer',
            'net_payment_term' => 'integer',
            'email_settings' => PostgresArray::class,
            'eu_tax_management' => 'boolean',
            'vat_rate' => 'float',
            'archived_at' => 'datetime',
            'einvoicing' => 'boolean',
            'payment_term' => 'array',
            'document_numbering' => EntityDocumentNumbering::class,
            'subscription_invoice_issuing_date_anchor' => SubscriptionInvoiceIssuingDateAnchor::class,
            'subscription_invoice_issuing_date_adjustment' => SubscriptionInvoiceIssuingDateAdjustment::class,
        ];
    }
}
