<?php

namespace App\Models;

use App\Models\BaseModel;
use App\Models\Casts\BcNumeric;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Frozen-schema model for `billing_entities`. Generated by scripts/gen-models.php;
 * refine relations, enums and domain methods as services are ported.
 */
class BillingEntity extends BaseModel
{
    use SoftDeletes;

    protected $table = 'billing_entities';

    protected $fillable = [
        'organization_id',
        'address_line1',
        'address_line2',
        'city',
        'country',
        'zipcode',
        'state',
        'timezone',
        'default_currency',
        'document_locale',
        'document_number_prefix',
        'document_numbering',
        'finalize_zero_amount_invoice',
        'invoice_footer',
        'invoice_grace_period',
        'net_payment_term',
        'email',
        'email_settings',
        'eu_tax_management',
        'legal_name',
        'legal_number',
        'logo',
        'name',
        'code',
        'tax_identification_number',
        'vat_rate',
        'archived_at',
        'applied_dunning_campaign_id',
        'einvoicing',
        'subscription_invoice_issuing_date_anchor',
        'subscription_invoice_issuing_date_adjustment',
        'phone',
        'payment_term',
    ];

    protected $casts = [
        'finalize_zero_amount_invoice' => 'boolean',
        'invoice_grace_period' => 'integer',
        'net_payment_term' => 'integer',
        'email_settings' => 'array',
        'eu_tax_management' => 'boolean',
        'vat_rate' => 'float',
        'archived_at' => 'datetime',
        'einvoicing' => 'boolean',
        'payment_term' => 'array',
    ];
}
