<?php

namespace App\Models;

use App\Models\BaseModel;
use App\Models\Casts\BcNumeric;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Frozen-schema model for `billable_metrics`. Generated by scripts/gen-models.php;
 * refine relations, enums and domain methods as services are ported.
 */
class BillableMetric extends BaseModel
{
    use SoftDeletes;

    protected $table = 'billable_metrics';

    protected $fillable = [
        'organization_id',
        'name',
        'code',
        'description',
        'properties',
        'aggregation_type',
        'field_name',
        'recurring',
        'weighted_interval',
        'custom_aggregator',
        'expression',
        'rounding_function',
        'rounding_precision',
    ];

    protected $casts = [
        'properties' => 'array',
        'aggregation_type' => 'integer',
        'recurring' => 'boolean',
        'rounding_precision' => 'integer',
    ];
}
