<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Frozen-schema model for `billable_metrics`. Generated by scripts/gen-models.php;
 * refine relations, enums and domain methods as services are ported.
 */
#[\Illuminate\Database\Eloquent\Attributes\Fillable([
    'organization_id',
    'name',
    'code',
    'description',
    'properties',
    'aggregation_type',
    'field_name',
    'recurring',
    'weighted_interval',
    'custom_aggregator',
    'expression',
    'rounding_function',
    'rounding_precision',
])]
#[\Illuminate\Database\Eloquent\Attributes\Table(name: 'billable_metrics')]
class BillableMetric extends BaseModel
{
    use SoftDeletes;

    protected function casts(): array
    {
        return [
            'properties' => 'array',
            'aggregation_type' => 'integer',
            'recurring' => 'boolean',
            'rounding_precision' => 'integer',
        ];
    }
}
