<?php

namespace App\Models;

use App\Models\BaseModel;
use App\Models\Casts\BcNumeric;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Frozen-schema model for `charge_filters`. Generated by scripts/gen-models.php;
 * refine relations, enums and domain methods as services are ported.
 */
class ChargeFilter extends BaseModel
{
    use SoftDeletes;

    protected $table = 'charge_filters';

    protected $fillable = [
        'charge_id',
        'properties',
        'invoice_display_name',
        'organization_id',
        'code',
    ];

    protected $casts = [
        'properties' => 'array',
    ];
}
