<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Frozen-schema model for `charge_filters`. Generated by scripts/gen-models.php;
 * refine relations, enums and domain methods as services are ported.
 */
#[\Illuminate\Database\Eloquent\Attributes\Fillable([
    'charge_id',
    'properties',
    'invoice_display_name',
    'organization_id',
    'code',
])]
#[\Illuminate\Database\Eloquent\Attributes\Table(name: 'charge_filters')]
class ChargeFilter extends BaseModel
{
    use SoftDeletes;

    protected function casts(): array
    {
        return [
            'properties' => 'array',
        ];
    }
}
