<?php

namespace App\Models;

use App\Models\BaseModel;
use App\Models\Casts\BcNumeric;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Frozen-schema model for `charges`. Generated by scripts/gen-models.php;
 * refine relations, enums and domain methods as services are ported.
 */
class Charge extends BaseModel
{
    use SoftDeletes;

    protected $table = 'charges';

    protected $fillable = [
        'billable_metric_id',
        'plan_id',
        'amount_currency',
        'charge_model',
        'properties',
        'pay_in_advance',
        'min_amount_cents',
        'invoiceable',
        'prorated',
        'invoice_display_name',
        'regroup_paid_fees',
        'parent_id',
        'organization_id',
        'code',
        'accepts_target_wallet',
    ];

    protected $casts = [
        'charge_model' => 'integer',
        'properties' => 'array',
        'pay_in_advance' => 'boolean',
        'min_amount_cents' => 'integer',
        'invoiceable' => 'boolean',
        'prorated' => 'boolean',
        'regroup_paid_fees' => 'integer',
        'accepts_target_wallet' => 'boolean',
    ];
}
