<?php

declare(strict_types=1);

namespace App\Models;

use App\Models\Casts\BcNumeric;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Frozen-schema model for `coupons`. Generated by scripts/gen-models.php;
 * refine relations, enums and domain methods as services are ported.
 */
#[\Illuminate\Database\Eloquent\Attributes\Fillable([
    'organization_id',
    'name',
    'code',
    'status',
    'terminated_at',
    'amount_cents',
    'amount_currency',
    'expiration',
    'coupon_type',
    'percentage_rate',
    'frequency',
    'frequency_duration',
    'expiration_at',
    'reusable',
    'limited_plans',
    'limited_billable_metrics',
    'description',
])]
#[\Illuminate\Database\Eloquent\Attributes\Table(name: 'coupons')]
class Coupon extends BaseModel
{
    use SoftDeletes;
    protected function casts(): array
    {
        return [
            'status' => 'integer',
            'terminated_at' => 'datetime',
            'amount_cents' => 'integer',
            'expiration' => 'integer',
            'coupon_type' => 'integer',
            'percentage_rate' => [BcNumeric::class, 'scale' => 5],
            'frequency' => 'integer',
            'frequency_duration' => 'integer',
            'expiration_at' => 'datetime',
            'reusable' => 'boolean',
            'limited_plans' => 'boolean',
            'limited_billable_metrics' => 'boolean',
        ];
    }
}
