<?php

namespace App\Models;

use App\Models\BaseModel;
use App\Models\Casts\BcNumeric;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Frozen-schema model for `coupons`. Generated by scripts/gen-models.php;
 * refine relations, enums and domain methods as services are ported.
 */
class Coupon extends BaseModel
{
    use SoftDeletes;

    protected $table = 'coupons';

    protected $fillable = [
        'organization_id',
        'name',
        'code',
        'status',
        'terminated_at',
        'amount_cents',
        'amount_currency',
        'expiration',
        'coupon_type',
        'percentage_rate',
        'frequency',
        'frequency_duration',
        'expiration_at',
        'reusable',
        'limited_plans',
        'limited_billable_metrics',
        'description',
    ];

    protected $casts = [
        'status' => 'integer',
        'terminated_at' => 'datetime',
        'amount_cents' => 'integer',
        'expiration' => 'integer',
        'coupon_type' => 'integer',
        'percentage_rate' => [BcNumeric::class, 'scale' => 5],
        'frequency' => 'integer',
        'frequency_duration' => 'integer',
        'expiration_at' => 'datetime',
        'reusable' => 'boolean',
        'limited_plans' => 'boolean',
        'limited_billable_metrics' => 'boolean',
    ];
}
