<?php

declare(strict_types=1);

namespace App\Models;

/**
 * Frozen-schema model for `credits`. Generated by scripts/gen-models.php;
 * refine relations, enums and domain methods as services are ported.
 */
#[\Illuminate\Database\Eloquent\Attributes\Fillable([
    'invoice_id',
    'applied_coupon_id',
    'amount_cents',
    'amount_currency',
    'credit_note_id',
    'before_taxes',
    'progressive_billing_invoice_id',
    'organization_id',
])]
#[\Illuminate\Database\Eloquent\Attributes\Table(name: 'credits')]
class Credit extends BaseModel
{
    protected function casts(): array
    {
        return [
            'amount_cents' => 'integer',
            'before_taxes' => 'boolean',
        ];
    }
}
