<?php

namespace App\Models;

use App\Models\BaseModel;
use App\Models\Casts\BcNumeric;

/**
 * Frozen-schema model for `credits`. Generated by scripts/gen-models.php;
 * refine relations, enums and domain methods as services are ported.
 */
class Credit extends BaseModel
{
    protected $table = 'credits';

    protected $fillable = [
        'invoice_id',
        'applied_coupon_id',
        'amount_cents',
        'amount_currency',
        'credit_note_id',
        'before_taxes',
        'progressive_billing_invoice_id',
        'organization_id',
    ];

    protected $casts = [
        'amount_cents' => 'integer',
        'before_taxes' => 'boolean',
    ];
}
