<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Attributes\Table;
use Illuminate\Database\Eloquent\Attributes\Fillable;

/**
 * Frozen-schema model for `customers_taxes`. Generated by scripts/gen-models.php;
 * refine relations, enums and domain methods as services are ported.
 */
#[Fillable([
    'customer_id',
    'tax_id',
    'organization_id',
])]
#[Table(name: 'customers_taxes')]
class CustomerTax extends BaseModel
{
    protected function casts(): array
    {
        return [

        ];
    }
}
