<?php

namespace App\Models;

use App\Models\BaseModel;

/**
 * Frozen-schema model for `customers_taxes`. Generated by scripts/gen-models.php;
 * refine relations, enums and domain methods as services are ported.
 */
class CustomerTax extends BaseModel
{
    protected $table = 'customers_taxes';

    protected $fillable = [
        'customer_id',
        'tax_id',
        'organization_id',
    ];

    protected $casts = [

    ];
}
