<?php

namespace App\Models;

use App\Models\BaseModel;
use App\Models\Casts\BcNumeric;

/**
 * Frozen-schema model for `customer_metadata`. Generated by scripts/gen-models.php;
 * refine relations, enums and domain methods as services are ported.
 */
class CustomerMetadata extends BaseModel
{
    protected $table = 'customer_metadata';

    protected $fillable = [
        'customer_id',
        'key',
        'value',
        'display_in_invoice',
        'organization_id',
    ];

    protected $casts = [
        'display_in_invoice' => 'boolean',
    ];
}
