<?php

declare(strict_types=1);

namespace App\Models;

use App\Enums\AccountType;
use App\Enums\CustomerType;
use App\Models\Concerns\Sequenced;
use App\Services\Validators\Countries;
use App\Services\Validators\Timezones;
use App\Services\Validators\Currencies;
use App\Enums\FinalizeZeroAmountInvoice;
use Illuminate\Support\Collection;
use Illuminate\Database\Eloquent\Builder;
use App\Services\Validators\EmailSanitizer;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Models\Concerns\BelongsToOrganization;
use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Attributes\Table;
use App\Enums\SubscriptionInvoiceIssuingDateAnchor;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use App\Enums\SubscriptionInvoiceIssuingDateAdjustment;
use Illuminate\Database\Eloquent\Relations\HasManyThrough;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

/**
 * Frozen-schema model for `customers`. Generated by scripts/gen-models.php;
 * refined with the Rails Customer model's relations, enums, scopes,
 * domain methods and validations.
 */
#[Fillable([
    'external_id',
    'name',
    'organization_id',
    'country',
    'address_line1',
    'address_line2',
    'state',
    'zipcode',
    'email',
    'city',
    'url',
    'phone',
    'logo_url',
    'legal_name',
    'legal_number',
    'vat_rate',
    'payment_provider',
    'slug',
    'sequential_id',
    'currency',
    'invoice_grace_period',
    'timezone',
    'document_locale',
    'tax_identification_number',
    'net_payment_term',
    'external_salesforce_id',
    'payment_provider_code',
    'shipping_address_line1',
    'shipping_address_line2',
    'shipping_city',
    'shipping_zipcode',
    'shipping_state',
    'shipping_country',
    'finalize_zero_amount_invoice',
    'firstname',
    'lastname',
    'customer_type',
    'applied_dunning_campaign_id',
    'exclude_from_dunning_campaign',
    'last_dunning_campaign_attempt',
    'last_dunning_campaign_attempt_at',
    'skip_invoice_custom_sections',
    'account_type',
    'billing_entity_id',
    'payment_receipt_counter',
    'subscription_invoice_issuing_date_anchor',
    'subscription_invoice_issuing_date_adjustment',
    'awaiting_wallet_refresh',
    'dunning_currency_attempts',
    'payment_term',
])]
#[Table(name: 'customers')]
class Customer extends BaseModel
{
    use BelongsToOrganization;
    use HasFactory;
    use Sequenced;
    use SoftDeletes;

    /** Rails: FINALIZE_ZERO_AMOUNT_INVOICE_OPTIONS. */
    public const FINALIZE_ZERO_AMOUNT_INVOICE_OPTIONS = ['inherit', 'skip', 'finalize'];

    /** Rails: CUSTOMER_TYPES. */
    public const CUSTOMER_TYPES = ['company', 'individual'];

    /** Rails: ACCOUNT_TYPES. */
    public const ACCOUNT_TYPES = ['customer', 'partner'];

    /** Rails: SUBSCRIPTION_INVOICE_ISSUING_DATE_ANCHORS. */
    public const SUBSCRIPTION_INVOICE_ISSUING_DATE_ANCHORS = ['current_period_end', 'next_period_start'];

    /** Rails: SUBSCRIPTION_INVOICE_ISSUING_DATE_ADJUSTMENTS. */
    public const SUBSCRIPTION_INVOICE_ISSUING_DATE_ADJUSTMENTS = ['keep_anchor', 'align_with_finalization_date'];

    /** Rails: PAYMENT_PROVIDERS. */
    public const PAYMENT_PROVIDERS = ['stripe', 'gocardless', 'cashfree', 'adyen', 'flutterwave', 'moneyhash'];

    /** Rails: SEARCHABLE_CUSTOMER_FIELDS. */
    public const SEARCHABLE_CUSTOMER_FIELDS = ['name', 'firstname', 'lastname', 'legal_name', 'external_id', 'email'];

    /** Rails: BILLING_ADDRESS_FIELDS. */
    public const BILLING_ADDRESS_FIELDS = ['address_line1', 'address_line2', 'city', 'zipcode', 'state', 'country'];

    /** Rails: SHIPPING_ADDRESS_FIELDS. */
    public const SHIPPING_ADDRESS_FIELDS = [
        'shipping_address_line1', 'shipping_address_line2', 'shipping_city',
        'shipping_zipcode', 'shipping_state', 'shipping_country',
    ];

    /** Rails: ADDRESS_FIELDS. */
    public const ADDRESS_FIELDS = [...self::BILLING_ADDRESS_FIELDS, ...self::SHIPPING_ADDRESS_FIELDS];

    /** Rails' I18n.available_locales (LanguageCodeValidator data). */
    public const AVAILABLE_LOCALES = ['en', 'fr', 'nb', 'de', 'it', 'es', 'sv', 'pt-BR', 'zh-TW'];

    /** Rails: the remaining `sanitize_null_bytes` fields (strip only). */
    public const NULL_BYTE_SANITIZED = [
        ...self::ADDRESS_FIELDS,
        'name', 'firstname', 'lastname', 'legal_name', 'legal_number',
        'phone', 'url', 'logo_url', 'tax_identification_number',
    ];

    /**
     * Rails' ActiveRecord carries the schema's column defaults in every new
     * instance; Eloquent does not, so the NOT NULL DEFAULT columns are
     * declared here to keep reads (and the serializers) identical to Rails.
     */
    protected $attributes = [
        'exclude_from_dunning_campaign' => false,
        'finalize_zero_amount_invoice' => 0,
        'skip_invoice_custom_sections' => false,
        'account_type' => 'customer',
        'awaiting_wallet_refresh' => false,
        'last_dunning_campaign_attempt' => 0,
        'payment_receipt_counter' => 0,
        'dunning_currency_attempts' => '{}',
    ];

    // -- Relationships --------------------------------------------------------

    public function invoices(): HasMany
    {
        return $this->hasMany(Invoice::class);
    }

    public function subscriptions(): HasMany
    {
        return $this->hasMany(Subscription::class);
    }

    public function billingEntity(): BelongsTo
    {
        return $this->belongsTo(BillingEntity::class);
    }

    /**
     * Rails: `has_many :applied_invoice_custom_sections,
     * class_name: "Customer::AppliedInvoiceCustomSection", dependent: :destroy`
     * (the `customers_invoice_custom_sections` table).
     */
    public function appliedInvoiceCustomSections(): HasMany
    {
        return $this->hasMany(CustomerAppliedInvoiceCustomSection::class, 'customer_id');
    }

    /** Rails: `has_many :selected_invoice_custom_sections, through: :applied_invoice_custom_sections, source: :invoice_custom_section`. */
    public function selectedInvoiceCustomSections(): BelongsToMany
    {
        return $this->belongsToMany(
            InvoiceCustomSection::class,
            'customers_invoice_custom_sections',
            'customer_id',
            'invoice_custom_section_id',
        )->whereNull('invoice_custom_sections.deleted_at');
    }

    /** Rails: `has_many :manual_selected_invoice_custom_sections, -> { where(section_type: :manual) }, through: ...`. */
    public function manualSelectedInvoiceCustomSections(): BelongsToMany
    {
        return $this->selectedInvoiceCustomSections()
            ->where('invoice_custom_sections.section_type', 'manual');
    }

    /** Rails: `has_many :system_generated_invoice_custom_sections, -> { where(section_type: :system_generated) }, through: ...`. */
    public function systemGeneratedInvoiceCustomSections(): BelongsToMany
    {
        return $this->selectedInvoiceCustomSections()
            ->where('invoice_custom_sections.section_type', 'system_generated');
    }

    /**
     * Rails: `applicable_invoice_custom_sections` — all manually selected
     * (configurable) sections plus any system-generated ones; the sections
     * that will actually appear on the invoice.
     */
    public function applicableInvoiceCustomSections(): Builder
    {
        $configurableIds = $this->configurableInvoiceCustomSections()->pluck('id')->all();
        $systemGeneratedIds = $this->systemGeneratedInvoiceCustomSections()->pluck('invoice_custom_sections.id')->all();

        return InvoiceCustomSection::query()
            ->where(function (Builder $query) use ($configurableIds, $systemGeneratedIds): void {
                $query->whereIn('id', $configurableIds)->orWhereIn('id', $systemGeneratedIds);
            });
    }

    /**
     * Rails: `configurable_invoice_custom_sections` — manually selected
     * sections: either directly configured on the customer, or the billing
     * entity's selection when the customer has none.
     *
     * @return Collection<int, InvoiceCustomSection>
     */
    public function configurableInvoiceCustomSections(): Collection
    {
        if ($this->skip_invoice_custom_sections) {
            return collect();
        }

        $manual = $this->manualSelectedInvoiceCustomSections()
            ->orderBy('invoice_custom_sections.name')
            ->get();

        if ($manual->isNotEmpty()) {
            return $manual;
        }

        return $this->billingEntity->selectedInvoiceCustomSections()
            ->orderBy('invoice_custom_sections.name')
            ->get();
    }

    /** Rails: `has_many :metadata, class_name: "Metadata::CustomerMetadata"`. */
    public function metadata(): HasMany
    {
        return $this->hasMany(CustomerMetadata::class);
    }

    /**
     * Rails: `has_many :applied_taxes, class_name: "Customer::AppliedTax"`
     * (the `customers_taxes` table).
     */
    public function appliedTaxes(): HasMany
    {
        return $this->hasMany(CustomerTax::class, 'customer_id');
    }

    /** Rails: `has_many :taxes, through: :applied_taxes`. */
    public function taxes(): HasManyThrough
    {
        return $this->hasManyThrough(
            Tax::class,
            CustomerTax::class,
            'customer_id',
            'id',
            'id',
            'tax_id',
        );
    }

    public function appliedCoupons(): HasMany
    {
        return $this->hasMany(AppliedCoupon::class);
    }

    /** Rails: `has_many :payment_provider_customers, class_name: "PaymentProviderCustomers::BaseCustomer"`. */
    public function paymentProviderCustomers(): HasMany
    {
        return $this->hasMany(PaymentProviderCustomer::class);
    }

    /** Rails: `has_many :payment_methods` (discarded methods are hidden). */
    public function paymentMethods(): HasMany
    {
        return $this->hasMany(PaymentMethod::class);
    }

    /** Rails: `has_many :integration_customers, class_name: "IntegrationCustomers::BaseCustomer"`. */
    public function integrationCustomers(): HasMany
    {
        return $this->hasMany(IntegrationCustomer::class);
    }

    /** Rails: `has_many :wallets`. */
    public function wallets(): HasMany
    {
        return $this->hasMany(Wallet::class);
    }

    // -- Domain methods (ports of the Rails instance methods) ------------------

    /** Rails: `partner_account?` (account_type enum suffix helper). */
    public function partnerAccount(): bool
    {
        return $this->getRawOriginal('account_type') === AccountType::Partner->value;
    }

    public function customerAccount(): bool
    {
        return $this->getRawOriginal('account_type') === AccountType::Customer->value;
    }

    /**
     * Rails: `flag_wallets_for_refresh` — marks the customer so the
     * wallet-refresh clock picks it up (a no-op without active wallets).
     */
    public function flagWalletsForRefresh(): void
    {
        if (! $this->wallets()->active()->exists()) {
            return;
        }

        $this->awaiting_wallet_refresh = true;
        $this->save();
    }

    /** Rails: `active_subscription` (status enum: pending=0, active=1, …). */
    public function activeSubscription(): ?Subscription
    {
        return $this->subscriptions()->where('status', 1)->latest('started_at')->first();
    }

    public function applicableTimezone(): string
    {
        if ($this->timezone !== null && $this->timezone !== '') {
            return $this->timezone;
        }

        return $this->billingEntity?->timezone ?? 'UTC';
    }

    public function applicableInvoiceGracePeriod(): int
    {
        if ($this->invoice_grace_period !== null) {
            return $this->invoice_grace_period;
        }

        return $this->billingEntity?->invoice_grace_period ?? 0;
    }

    public function applicableNetPaymentTerm(): ?int
    {
        if ($this->net_payment_term !== null) {
            return $this->net_payment_term;
        }

        return $this->billingEntity?->net_payment_term;
    }

    public function applicableSubscriptionInvoiceIssuingDateAnchor(): ?string
    {
        $own = $this->getRawOriginal('subscription_invoice_issuing_date_anchor');

        return $own ?? $this->billingEntity?->getRawOriginal('subscription_invoice_issuing_date_anchor');
    }

    public function applicableSubscriptionInvoiceIssuingDateAdjustment(): ?string
    {
        $own = $this->getRawOriginal('subscription_invoice_issuing_date_adjustment');

        return $own ?? $this->billingEntity?->getRawOriginal('subscription_invoice_issuing_date_adjustment');
    }

    /**
     * Rails: `editable?` — customers already attached to billing objects can
     * no longer change identity fields.
     *
     * TODO(port): applied_add_ons and wallets have no models yet — treated as
     * empty, matching a customer that has none.
     */
    public function editable(): bool
    {
        return $this->subscriptions()->doesntExist()
            && $this->invoices()->doesntExist()
            && $this->appliedCoupons()->whereNotNull('amount_currency')->doesntExist();
    }

    /**
     * Rails: `shipping_address` — the six shipping columns as a hash.
     *
     * @return array<string, string|null>
     */
    public function shippingAddress(): array
    {
        return [
            'address_line1' => $this->shipping_address_line1,
            'address_line2' => $this->shipping_address_line2,
            'city' => $this->shipping_city,
            'zipcode' => $this->shipping_zipcode,
            'state' => $this->shipping_state,
            'country' => $this->shipping_country,
        ];
    }

    /** Rails: `address_changed?` over BILLING + SHIPPING address fields. */
    public function addressChanged(): bool
    {
        foreach (self::ADDRESS_FIELDS as $field) {
            if ($this->isDirty($field)) {
                return true;
            }
        }

        return false;
    }

    /**
     * Rails: `preferred_document_locale` — the customer's document locale,
     * falling back to the billing entity's.
     */
    public function preferredDocumentLocale(): ?string
    {
        return $this->document_locale ?: $this->billingEntity?->document_locale;
    }

    /**
     * Rails: `tax_customer` — the customer's tax provider connection (anrok
     * or avalara integration customer), or nil.
     */
    public function taxCustomer(): ?\App\Models\IntegrationCustomer
    {
        return $this->integrationCustomers()
            ->whereIn('type', \App\Models\IntegrationCustomer::PROVIDER_TYPES)
            ->first();
    }

    /**
     * Rails: `effective_shipping_address` — the shipping columns falling back
     * to the billing address ones.
     *
     * @return array<string, string|null>
     */
    public function effectiveShippingAddress(): array
    {
        return [
            'address_line1' => $this->shipping_address_line1 ?: $this->address_line1,
            'address_line2' => $this->shipping_address_line2 ?: $this->address_line2,
            'city' => $this->shipping_city ?: $this->city,
            'zipcode' => $this->shipping_zipcode ?: $this->zipcode,
            'state' => $this->shipping_state ?: $this->state,
            'country' => $this->shipping_country ?: $this->country,
        ];
    }

    /** Rails: `taxable?` — a tax identification number makes the contact taxable. */
    public function taxable(): bool
    {
        return $this->tax_identification_number !== null && $this->tax_identification_number !== '';
    }

    // -- Validations ------------------------------------------------------------

    /**
     * Port of the Rails model validations — `field => [api error codes]`,
     * empty when valid.
     *
     * @return array<string, list<string>>
     */
    public function validateAttributes(): array
    {
        $errors = [];

        if ($this->country !== null && ! Countries::valid($this->country)) {
            $errors['country'] = ['not_a_valid_country_code'];
        }

        if ($this->shipping_country !== null && ! Countries::valid($this->shipping_country)) {
            $errors['shipping_country'] = ['not_a_valid_country_code'];
        }

        if ($this->document_locale !== null && ! in_array($this->document_locale, self::AVAILABLE_LOCALES, true)) {
            $errors['document_locale'] = ['not_a_valid_language_code'];
        }

        if ($this->currency !== null && ! Currencies::valid($this->currency)) {
            $errors['currency'] = ['value_is_invalid'];
        }

        if ($this->name !== null && mb_strlen($this->name) > 255) {
            $errors['name'] = ['value_is_too_long'];
        }

        if (($this->external_id ?? '') === '') {
            $errors['external_id'] = ['value_is_mandatory'];
        } else {
            $uniqueness = static::query()
                ->where('external_id', $this->external_id)
                ->where('organization_id', $this->organization_id)
                ->whereNull('deleted_at');

            if ($this->exists) {
                $uniqueness->where($this->getKeyName(), '!=', $this->getKey());
            }

            if ($uniqueness->exists()) {
                $errors['external_id'] = ['value_already_exist'];
            }
        }

        foreach (['invoice_grace_period' => $this->invoice_grace_period, 'net_payment_term' => $this->net_payment_term] as $field => $value) {
            if ($value !== null && $value < 0) {
                $errors[$field] = ['value_is_out_of_range'];
            }
        }

        if ($this->payment_provider !== null && ! in_array($this->payment_provider, self::PAYMENT_PROVIDERS, true)) {
            $errors['payment_provider'] = ['value_is_invalid'];
        }

        if ($this->getRawOriginal('timezone') !== null && ! Timezones::valid($this->getRawOriginal('timezone'))) {
            $errors['timezone'] = ['invalid_timezone'];
        }

        if ($this->email !== null && $this->email !== '' && $this->isDirty('email') && ! EmailSanitizer::valid($this->email)) {
            $errors['email'] = ['invalid_email_format'];
        }

        $customerType = $this->getRawOriginal('customer_type');

        if ($customerType !== null && ! in_array($customerType, self::CUSTOMER_TYPES, true)) {
            $errors['customer_type'] = ['value_is_invalid'];
        }

        $accountType = $this->getRawOriginal('account_type');

        if ($accountType !== null && ! in_array($accountType, self::ACCOUNT_TYPES, true)) {
            $errors['account_type'] = ['value_is_invalid'];
        }

        $anchor = $this->getRawOriginal('subscription_invoice_issuing_date_anchor');

        if ($anchor !== null && ! in_array($anchor, self::SUBSCRIPTION_INVOICE_ISSUING_DATE_ANCHORS, true)) {
            $errors['subscription_invoice_issuing_date_anchor'] = ['value_is_invalid'];
        }

        $adjustment = $this->getRawOriginal('subscription_invoice_issuing_date_adjustment');

        if ($adjustment !== null && ! in_array($adjustment, self::SUBSCRIPTION_INVOICE_ISSUING_DATE_ADJUSTMENTS, true)) {
            $errors['subscription_invoice_issuing_date_adjustment'] = ['value_is_invalid'];
        }

        return $errors;
    }

    // -- Attribute behavior ---------------------------------------------------

    /**
     * Port of NullByteSanitizable (app/models/concerns/null_byte_sanitizable.rb):
     * strips PostgreSQL-incompatible NULL bytes from string attributes on
     * assignment so a null byte becomes clean stored data instead of a 500.
     * Address fields keep the historical blank -> nil behavior; identity/
     * free-text fields are only stripped so existing empty-string values are
     * preserved.
     */
    public function setAttribute($key, $value)
    {
        if (is_string($value) && in_array($key, self::NULL_BYTE_SANITIZED, true)) {
            $value = str_replace("\0", '', $value);

            if (in_array($key, self::ADDRESS_FIELDS, true) && $value === '') {
                $value = null;
            }
        }

        return parent::setAttribute($key, $value);
    }

    // -- dunning campaigns slice (appended) -----------------------------------

    /** Rails: belongs_to :applied_dunning_campaign, optional: true. */
    public function appliedDunningCampaign(): BelongsTo
    {
        return $this->belongsTo(DunningCampaign::class, 'applied_dunning_campaign_id');
    }

    /**
     * Rails: scope :falling_back_to_default_dunning_campaign — customers
     * with no explicit campaign that are not excluded from dunning (they
     * resolve the billing entity's applied campaign at runtime).
     */
    public function scopeFallingBackToDefaultDunningCampaign($query)
    {
        return $query->whereNull('applied_dunning_campaign_id')
            ->where('exclude_from_dunning_campaign', false);
    }

    /** Rails: overdue_balance_cents — non-self-billed overdue invoice sum in a currency. */
    public function overdueBalanceCents(?string $forCurrency = null): int
    {
        return (int) $this->overdueInvoicesQuery($forCurrency ?? $this->currency)
            ->sum('total_amount_cents');
    }

    /** Rails: overdue_balances — {currency => total_amount_cents} of overdue invoices. */
    public function overdueBalances(): array
    {
        return $this->overdueInvoicesQuery()
            ->groupBy('currency')
            ->selectRaw('currency, SUM(total_amount_cents) as amount_cents')
            ->pluck('amount_cents', 'currency')
            ->map(fn ($cents) => (int) $cents)
            ->all();
    }

    /** Rails: reset_dunning_campaign! */
    public function resetDunningCampaign(): void
    {
        $this->forceFill([
            'dunning_currency_attempts' => [],
            'last_dunning_campaign_attempt' => 0,
            'last_dunning_campaign_attempt_at' => null,
        ])->save();
    }

    /**
     * Rails: reset_dunning_campaign_for_currency! — zero the per-currency
     * attempt counter; `last_dunning_campaign_attempt_at` only clears when
     * every tracked currency is back at zero.
     */
    public function resetDunningCampaignForCurrency(string $currency): void
    {
        $attempts = $this->dunning_currency_attempts ?? [];
        $attempts[$currency] = 0;

        $allReset = count($attempts) > 0 && count(array_filter($attempts, fn ($v) => (int) $v !== 0)) === 0;

        $this->forceFill([
            'dunning_currency_attempts' => $attempts,
            'last_dunning_campaign_attempt' => 0,
            'last_dunning_campaign_attempt_at' => $allReset ? null : $this->last_dunning_campaign_attempt_at,
        ])->save();
    }

    // -- Lifecycle ------------------------------------------------------------

    protected static function booted(): void
    {
        // Rails: before_save :ensure_slug
        static::saving(function (self $customer): void {
            $customer->ensureSlug();
        });
    }

    // -- Sequenced (Rails: `sequenced scope: ->(customer) { customer.organization.customers.with_discarded },
    //    lock_key: ->(customer) { customer.organization_id }`) ----------------

    protected function sequenceScope(): Builder
    {
        // with_discarded — include soft-deleted customers in the numbering.
        return static::query()->withTrashed()->where('organization_id', $this->organization_id);
    }

    protected function sequencedLockKey(): ?string
    {
        return (string) $this->organization_id;
    }

    /**
     * Rails: `slug = "#{organization.document_number_prefix}-#{format('%03d', sequential_id)}"`
     * when blank.
     */
    protected function ensureSlug(): void
    {
        if ($this->slug !== null && $this->slug !== '') {
            return;
        }

        $prefix = $this->organization?->document_number_prefix;

        if ($prefix === null) {
            return;
        }

        $this->slug = $prefix.'-'.sprintf('%03d', (int) $this->sequential_id);
    }

    protected function email(): Attribute
    {
        return Attribute::set(fn (?string $value) => EmailSanitizer::sanitize($value));
    }

    protected function casts(): array
    {
        return [
            'vat_rate' => 'float',
            'sequential_id' => 'integer',
            'invoice_grace_period' => 'integer',
            'net_payment_term' => 'integer',
            'finalize_zero_amount_invoice' => FinalizeZeroAmountInvoice::class,
            'exclude_from_dunning_campaign' => 'boolean',
            'last_dunning_campaign_attempt' => 'integer',
            'last_dunning_campaign_attempt_at' => 'datetime',
            'skip_invoice_custom_sections' => 'boolean',
            'payment_receipt_counter' => 'integer',
            'awaiting_wallet_refresh' => 'boolean',
            'dunning_currency_attempts' => 'array',
            'payment_term' => 'array',
            'customer_type' => CustomerType::class,
            'account_type' => AccountType::class,
            'subscription_invoice_issuing_date_anchor' => SubscriptionInvoiceIssuingDateAnchor::class,
            'subscription_invoice_issuing_date_adjustment' => SubscriptionInvoiceIssuingDateAdjustment::class,
        ];
    }

    private function overdueInvoicesQuery(?string $currency = null)
    {
        return $this->invoices()
            ->where('self_billed', false)
            ->where('payment_overdue', true)
            ->when($currency !== null, fn ($q) => $q->where('currency', $currency));
    }
}
