<?php

namespace App\Models;

use App\Models\BaseModel;
use App\Models\Casts\BcNumeric;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Frozen-schema model for `customers`. Generated by scripts/gen-models.php;
 * refine relations, enums and domain methods as services are ported.
 */
class Customer extends BaseModel
{
    use SoftDeletes;

    protected $table = 'customers';

    protected $fillable = [
        'external_id',
        'name',
        'organization_id',
        'country',
        'address_line1',
        'address_line2',
        'state',
        'zipcode',
        'email',
        'city',
        'url',
        'phone',
        'logo_url',
        'legal_name',
        'legal_number',
        'vat_rate',
        'payment_provider',
        'slug',
        'sequential_id',
        'currency',
        'invoice_grace_period',
        'timezone',
        'document_locale',
        'tax_identification_number',
        'net_payment_term',
        'external_salesforce_id',
        'payment_provider_code',
        'shipping_address_line1',
        'shipping_address_line2',
        'shipping_city',
        'shipping_zipcode',
        'shipping_state',
        'shipping_country',
        'finalize_zero_amount_invoice',
        'firstname',
        'lastname',
        'customer_type',
        'applied_dunning_campaign_id',
        'exclude_from_dunning_campaign',
        'last_dunning_campaign_attempt',
        'last_dunning_campaign_attempt_at',
        'skip_invoice_custom_sections',
        'account_type',
        'billing_entity_id',
        'payment_receipt_counter',
        'subscription_invoice_issuing_date_anchor',
        'subscription_invoice_issuing_date_adjustment',
        'awaiting_wallet_refresh',
        'dunning_currency_attempts',
        'payment_term',
    ];

    public function invoices()
    {
        return $this->hasMany(\App\Models\Invoice::class);
    }

    protected $casts = [
        'vat_rate' => 'float',
        'sequential_id' => 'integer',
        'invoice_grace_period' => 'integer',
        'net_payment_term' => 'integer',
        'finalize_zero_amount_invoice' => 'integer',
        'exclude_from_dunning_campaign' => 'boolean',
        'last_dunning_campaign_attempt' => 'integer',
        'last_dunning_campaign_attempt_at' => 'datetime',
        'skip_invoice_custom_sections' => 'boolean',
        'payment_receipt_counter' => 'integer',
        'awaiting_wallet_refresh' => 'boolean',
        'dunning_currency_attempts' => 'array',
        'payment_term' => 'array',
    ];
}
