<?php

declare(strict_types=1);

namespace App\Models;

/**
 * Frozen-schema model for `customers_taxes`. Generated by scripts/gen-models.php;
 * refine relations, enums and domain methods as services are ported.
 */
#[\Illuminate\Database\Eloquent\Attributes\Fillable([
    'customer_id',
    'tax_id',
    'organization_id',
])]
#[\Illuminate\Database\Eloquent\Attributes\Table(name: 'customers_taxes')]
class CustomerTax extends BaseModel
{
    protected function casts(): array
    {
        return [
    
        ];
    }
}
