<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Models\Concerns\BelongsToOrganization;
use Illuminate\Database\Eloquent\Attributes\Table;
use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Factories\HasFactory;

/**
 * Frozen-schema model for `events`. Generated by scripts/gen-models.php;
 * refined with the Rails Event model's behaviors
 * (app/models/event.rb).
 *
 * Rails uses Discard (default_scope { kept }) — the Laravel equivalent is
 * SoftDeletes on `deleted_at`, so discarded events read as missing.
 *
 * NOTE: `precise_total_amount_cents` is deliberately NOT cast with
 * BcNumeric: the REST serializer must reproduce Rails'
 * `BigDecimal#to_s` of the ASSIGNED value (e.g. "0.12345e3" for
 * "123.45") — a scale-15 cast would add trailing zeros the API must not
 * emit. The column is not used in billing math on this table.
 */
#[Fillable([
    'organization_id',
    'customer_id',
    'transaction_id',
    'code',
    'properties',
    'timestamp',
    'metadata',
    'subscription_id',
    'external_customer_id',
    'external_subscription_id',
    'precise_total_amount_cents',
])]
#[Table(name: 'events')]
class Event extends BaseModel
{
    use BelongsToOrganization;
    use HasFactory;
    use SoftDeletes;

    protected $attributes = [
        'properties' => '{}',
        'metadata' => '{}',
    ];

    protected $casts = [
        'properties' => 'array',
        'metadata' => 'array',
        'timestamp' => 'datetime',
    ];

    // -- Scopes (Rails: app/models/event.rb) ----------------------------------

    /** Rails: `scope :from_datetime` */
    public function scopeFromDatetime(Builder $query, $fromDatetime): Builder
    {
        return $query->where('timestamp', '>=', $fromDatetime);
    }

    /** Rails: `scope :to_datetime` */
    public function scopeToDatetime(Builder $query, $toDatetime): Builder
    {
        return $query->where('timestamp', '<=', $toDatetime);
    }

    // -- Domain methods (Rails: app/models/event.rb) --------------------------

    /** Rails: `api_client` — the user agent recorded in the event metadata. */
    public function apiClient(): ?string
    {
        return $this->metadata['user_agent'] ?? null;
    }

    /** Rails: `ip_address` — the remote ip recorded in the event metadata. */
    public function ipAddress(): ?string
    {
        return $this->metadata['ip_address'] ?? null;
    }
}
