<?php

declare(strict_types=1);

namespace App\Models;

use App\Models\Casts\BcNumeric;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Frozen-schema model for `fees`. Generated by scripts/gen-models.php;
 * refine relations, enums and domain methods as services are ported.
 */
#[\Illuminate\Database\Eloquent\Attributes\Fillable([
    'invoice_id',
    'charge_id',
    'subscription_id',
    'amount_cents',
    'amount_currency',
    'taxes_amount_cents',
    'taxes_rate',
    'units',
    'applied_add_on_id',
    'properties',
    'fee_type',
    'invoiceable_type',
    'invoiceable_id',
    'events_count',
    'group_id',
    'pay_in_advance_event_id',
    'payment_status',
    'succeeded_at',
    'failed_at',
    'refunded_at',
    'true_up_parent_fee_id',
    'add_on_id',
    'description',
    'unit_amount_cents',
    'pay_in_advance',
    'precise_coupons_amount_cents',
    'total_aggregated_units',
    'invoice_display_name',
    'precise_unit_amount',
    'amount_details',
    'charge_filter_id',
    'grouped_by',
    'pay_in_advance_event_transaction_id',
    'precise_amount_cents',
    'taxes_precise_amount_cents',
    'taxes_base_rate',
    'organization_id',
    'billing_entity_id',
    'precise_credit_notes_amount_cents',
    'fixed_charge_id',
    'duplicated_in_advance',
    'original_fee_id',
    'rate_card_rate_id',
    'rate_override_id',
    'product_filter_id',
    'contract_id',
    'contract_rate_card_id',
])]
#[\Illuminate\Database\Eloquent\Attributes\Table(name: 'fees')]
class Fee extends BaseModel
{
    use SoftDeletes;

    protected function casts(): array
    {
        return [
            'amount_cents' => 'integer',
            'taxes_amount_cents' => 'integer',
            'taxes_rate' => 'float',
            'units' => [BcNumeric::class, 'scale' => 0],
            'properties' => 'array',
            'fee_type' => 'integer',
            'events_count' => 'integer',
            'payment_status' => 'integer',
            'succeeded_at' => 'datetime',
            'failed_at' => 'datetime',
            'refunded_at' => 'datetime',
            'unit_amount_cents' => 'integer',
            'pay_in_advance' => 'boolean',
            'precise_coupons_amount_cents' => [BcNumeric::class, 'scale' => 5],
            'total_aggregated_units' => [BcNumeric::class, 'scale' => 0],
            'precise_unit_amount' => [BcNumeric::class, 'scale' => 15],
            'amount_details' => 'array',
            'grouped_by' => 'array',
            'precise_amount_cents' => [BcNumeric::class, 'scale' => 15],
            'taxes_precise_amount_cents' => [BcNumeric::class, 'scale' => 15],
            'taxes_base_rate' => 'float',
            'precise_credit_notes_amount_cents' => [BcNumeric::class, 'scale' => 5],
            'duplicated_in_advance' => 'boolean',
        ];
    }
}
