<?php

declare(strict_types=1);

namespace App\Models;

use App\Models\Casts\BcNumeric;
use Illuminate\Database\Eloquent\Attributes\Table;
use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Factories\HasFactory;

/**
 * Frozen-schema model for `fees_taxes`. Generated by scripts/gen-models.php;
 * refine relations, enums and domain methods as services are ported.
 */
#[Fillable([
    'fee_id',
    'tax_id',
    'tax_description',
    'tax_code',
    'tax_name',
    'tax_rate',
    'amount_cents',
    'amount_currency',
    'precise_amount_cents',
    'organization_id',
])]
#[Table(name: 'fees_taxes')]
class FeeAppliedTax extends BaseModel
{
    use HasFactory;

    public function fee()
    {
        return $this->belongsTo(Fee::class);
    }

    public function tax()
    {
        return $this->belongsTo(Tax::class);
    }

    protected function casts(): array
    {
        return [
            'tax_rate' => 'float',
            'amount_cents' => 'integer',
            'precise_amount_cents' => [BcNumeric::class, 'scale' => 15],
        ];
    }
}
