<?php

namespace App\Models;

use App\Models\BaseModel;
use App\Models\Casts\BcNumeric;

/**
 * Frozen-schema model for `fees_taxes`. Generated by scripts/gen-models.php;
 * refine relations, enums and domain methods as services are ported.
 */
class FeeAppliedTax extends BaseModel
{
    protected $table = 'fees_taxes';

    protected $fillable = [
        'fee_id',
        'tax_id',
        'tax_description',
        'tax_code',
        'tax_name',
        'tax_rate',
        'amount_cents',
        'amount_currency',
        'precise_amount_cents',
        'organization_id',
    ];

    protected $casts = [
        'tax_rate' => 'float',
        'amount_cents' => 'integer',
        'precise_amount_cents' => [BcNumeric::class, 'scale' => 15],
    ];
}
