<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;

/**
 * Frozen-schema model for `invoices`. Generated by scripts/gen-models.php;
 * refine relations, enums and domain methods as services are ported.
 */
#[\Illuminate\Database\Eloquent\Attributes\Fillable([
    'issuing_date',
    'taxes_amount_cents',
    'total_amount_cents',
    'invoice_type',
    'payment_status',
    'number',
    'sequential_id',
    'file',
    'customer_id',
    'taxes_rate',
    'status',
    'timezone',
    'payment_attempts',
    'ready_for_payment_processing',
    'organization_id',
    'version_number',
    'currency',
    'fees_amount_cents',
    'coupons_amount_cents',
    'credit_notes_amount_cents',
    'prepaid_credit_amount_cents',
    'sub_total_excluding_taxes_amount_cents',
    'sub_total_including_taxes_amount_cents',
    'payment_due_date',
    'net_payment_term',
    'voided_at',
    'organization_sequential_id',
    'ready_to_be_refreshed',
    'payment_dispute_lost_at',
    'skip_charges',
    'payment_overdue',
    'negative_amount_cents',
    'progressive_billing_credit_amount_cents',
    'tax_status',
    'total_paid_amount_cents',
    'self_billed',
    'applied_grace_period',
    'billing_entity_id',
    'billing_entity_sequential_id',
    'finalized_at',
    'voided_invoice_id',
    'xml_file',
    'expected_finalization_date',
    'prepaid_granted_credit_amount_cents',
    'prepaid_purchased_credit_amount_cents',
    'payment_method_id',
    'skip_automatic_payment',
    'purchase_order_number',
    'payment_term',
    'payment_term_source',
    'search_terms',
])]
#[\Illuminate\Database\Eloquent\Attributes\Table(name: 'invoices')]
class Invoice extends BaseModel
{
    use Concerns\Sequenced;

    public function customer()
    {
        return $this->belongsTo(Customer::class);
    }

    /**
     * Port of: sequenced scope: ->(invoice) { invoice.customer.invoices.where(billing_entity_id:) },
     *          lock_key: ->(invoice) { "#{invoice.customer_id}-#{invoice.billing_entity_id}" }
     */
    protected function sequenceScope(): Builder
    {
        return $this->customer->invoices()->getQuery()->where('billing_entity_id', $this->billing_entity_id);
    }

    protected function sequencedLockKey(): ?string
    {
        return $this->customer_id.'-'.$this->billing_entity_id;
    }
    protected function casts(): array
    {
        return [
            'issuing_date' => 'date:Y-m-d',
            'taxes_amount_cents' => 'integer',
            'total_amount_cents' => 'integer',
            'invoice_type' => 'integer',
            'payment_status' => 'integer',
            'sequential_id' => 'integer',
            'taxes_rate' => 'float',
            'status' => 'integer',
            'payment_attempts' => 'integer',
            'ready_for_payment_processing' => 'boolean',
            'version_number' => 'integer',
            'fees_amount_cents' => 'integer',
            'coupons_amount_cents' => 'integer',
            'credit_notes_amount_cents' => 'integer',
            'prepaid_credit_amount_cents' => 'integer',
            'sub_total_excluding_taxes_amount_cents' => 'integer',
            'sub_total_including_taxes_amount_cents' => 'integer',
            'payment_due_date' => 'date:Y-m-d',
            'net_payment_term' => 'integer',
            'voided_at' => 'datetime',
            'organization_sequential_id' => 'integer',
            'ready_to_be_refreshed' => 'boolean',
            'payment_dispute_lost_at' => 'datetime',
            'skip_charges' => 'boolean',
            'payment_overdue' => 'boolean',
            'negative_amount_cents' => 'integer',
            'progressive_billing_credit_amount_cents' => 'integer',
            'total_paid_amount_cents' => 'integer',
            'self_billed' => 'boolean',
            'applied_grace_period' => 'integer',
            'billing_entity_sequential_id' => 'integer',
            'finalized_at' => 'datetime',
            'expected_finalization_date' => 'date:Y-m-d',
            'prepaid_granted_credit_amount_cents' => 'integer',
            'prepaid_purchased_credit_amount_cents' => 'integer',
            'skip_automatic_payment' => 'boolean',
            'payment_term' => 'array',
        ];
    }
}
