<?php

declare(strict_types=1);

namespace App\Models;

/**
 * Frozen-schema model for `invoice_subscriptions`. Generated by scripts/gen-models.php;
 * refine relations, enums and domain methods as services are ported.
 */
#[\Illuminate\Database\Eloquent\Attributes\Fillable([
    'invoice_id',
    'subscription_id',
    'recurring',
    'timestamp',
    'from_datetime',
    'to_datetime',
    'charges_from_datetime',
    'charges_to_datetime',
    'invoicing_reason',
    'organization_id',
    'regenerated_invoice_id',
    'fixed_charges_from_datetime',
    'fixed_charges_to_datetime',
])]
#[\Illuminate\Database\Eloquent\Attributes\Table(name: 'invoice_subscriptions')]
class InvoiceSubscription extends BaseModel
{
    protected function casts(): array
    {
        return [
            'recurring' => 'boolean',
            'timestamp' => 'datetime',
            'from_datetime' => 'datetime',
            'to_datetime' => 'datetime',
            'charges_from_datetime' => 'datetime',
            'charges_to_datetime' => 'datetime',
            'fixed_charges_from_datetime' => 'datetime',
            'fixed_charges_to_datetime' => 'datetime',
        ];
    }
}
