<?php

namespace App\Models;

use App\Models\BaseModel;
use App\Models\Casts\BcNumeric;

/**
 * Frozen-schema model for `invoice_subscriptions`. Generated by scripts/gen-models.php;
 * refine relations, enums and domain methods as services are ported.
 */
class InvoiceSubscription extends BaseModel
{
    protected $table = 'invoice_subscriptions';

    protected $fillable = [
        'invoice_id',
        'subscription_id',
        'recurring',
        'timestamp',
        'from_datetime',
        'to_datetime',
        'charges_from_datetime',
        'charges_to_datetime',
        'invoicing_reason',
        'organization_id',
        'regenerated_invoice_id',
        'fixed_charges_from_datetime',
        'fixed_charges_to_datetime',
    ];

    protected $casts = [
        'recurring' => 'boolean',
        'timestamp' => 'datetime',
        'from_datetime' => 'datetime',
        'to_datetime' => 'datetime',
        'charges_from_datetime' => 'datetime',
        'charges_to_datetime' => 'datetime',
        'fixed_charges_from_datetime' => 'datetime',
        'fixed_charges_to_datetime' => 'datetime',
    ];
}
