<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Frozen-schema model for `membership_roles`. Generated by scripts/gen-models.php;
 * refine relations, enums and domain methods as services are ported.
 */
#[\Illuminate\Database\Eloquent\Attributes\Fillable([
    'organization_id',
    'membership_id',
    'role_id',
])]
#[\Illuminate\Database\Eloquent\Attributes\Table(name: 'membership_roles')]
class MembershipRole extends BaseModel
{
    use SoftDeletes;

    protected function casts(): array
    {
        return [

        ];
    }
}
