<?php

namespace App\Models;

use App\Models\BaseModel;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Frozen-schema model for `membership_roles`. Generated by scripts/gen-models.php;
 * refine relations, enums and domain methods as services are ported.
 */
class MembershipRole extends BaseModel
{
    use SoftDeletes;

    protected $table = 'membership_roles';

    protected $fillable = [
        'organization_id',
        'membership_id',
        'role_id',
    ];

    protected $casts = [

    ];
}
