<?php

namespace App\Models;

use App\Models\BaseModel;
use App\Models\Casts\BcNumeric;

/**
 * Frozen-schema model for `memberships`. Generated by scripts/gen-models.php;
 * refine relations, enums and domain methods as services are ported.
 */
class Membership extends BaseModel
{
    protected $table = 'memberships';

    protected $fillable = [
        'organization_id',
        'user_id',
        'status',
        'revoked_at',
    ];

    protected $casts = [
        'status' => 'integer',
        'revoked_at' => 'datetime',
    ];
}
