<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Frozen-schema model for `plans`. Generated by scripts/gen-models.php;
 * refine relations, enums and domain methods as services are ported.
 */
#[\Illuminate\Database\Eloquent\Attributes\Fillable([
    'organization_id',
    'name',
    'code',
    'interval',
    'description',
    'amount_cents',
    'amount_currency',
    'trial_period',
    'pay_in_advance',
    'bill_charges_monthly',
    'parent_id',
    'pending_deletion',
    'invoice_display_name',
    'bill_fixed_charges_monthly',
])]
#[\Illuminate\Database\Eloquent\Attributes\Table(name: 'plans')]
class Plan extends BaseModel
{
    use SoftDeletes;

    protected function casts(): array
    {
        return [
            'interval' => 'integer',
            'amount_cents' => 'integer',
            'trial_period' => 'float',
            'pay_in_advance' => 'boolean',
            'bill_charges_monthly' => 'boolean',
            'pending_deletion' => 'boolean',
            'bill_fixed_charges_monthly' => 'boolean',
        ];
    }
}
