<?php

namespace App\Models;

use App\Models\BaseModel;
use App\Models\Casts\BcNumeric;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Frozen-schema model for `plans`. Generated by scripts/gen-models.php;
 * refine relations, enums and domain methods as services are ported.
 */
class Plan extends BaseModel
{
    use SoftDeletes;

    protected $table = 'plans';

    protected $fillable = [
        'organization_id',
        'name',
        'code',
        'interval',
        'description',
        'amount_cents',
        'amount_currency',
        'trial_period',
        'pay_in_advance',
        'bill_charges_monthly',
        'parent_id',
        'pending_deletion',
        'invoice_display_name',
        'bill_fixed_charges_monthly',
    ];

    protected $casts = [
        'interval' => 'integer',
        'amount_cents' => 'integer',
        'trial_period' => 'float',
        'pay_in_advance' => 'boolean',
        'bill_charges_monthly' => 'boolean',
        'pending_deletion' => 'boolean',
        'bill_fixed_charges_monthly' => 'boolean',
    ];
}
