<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Attributes\Table;
use Illuminate\Database\Eloquent\Attributes\Fillable;

/**
 * Frozen-schema model for `pricing_units`. Generated by scripts/gen-models.php;
 * refined with the Rails model's validations. The table carries no
 * `deleted_at` (Rails' PricingUnit is not discardable).
 */
#[Fillable([
    'name',
    'code',
    'short_name',
    'description',
    'organization_id',
])]
#[Table(name: 'pricing_units')]
class PricingUnit extends BaseModel
{
    /**
     * Port of Rails' PricingUnit validations (app/models/pricing_unit.rb):
     * name/code/short_name presence, code uniqueness per organization,
     * description up to 600 characters, short_name up to 3.
     *
     * @return array<string, list<string>>
     */
    public function validateAttributes(): array
    {
        $errors = [];

        foreach (['name', 'code', 'short_name'] as $attribute) {
            if (($this->{$attribute} ?? '') === '') {
                $errors[$attribute] = ['value_is_mandatory'];
            }
        }

        if (($this->code ?? '') !== '') {
            // Rails: uniqueness {scope: :organization_id}.
            $uniqueness = static::query()
                ->where('code', $this->code)
                ->where('organization_id', $this->organization_id);

            if ($this->exists) {
                $uniqueness->where($this->getKeyName(), '!=', $this->getKey());
            }

            if ($uniqueness->exists()) {
                $errors['code'] = ['value_already_exist'];
            }
        }

        if (($this->description ?? '') !== '' && mb_strlen($this->description) > 600) {
            $errors['description'] = ['invalid_length'];
        }

        if (($this->short_name ?? '') !== '' && mb_strlen($this->short_name) > 3) {
            $errors['short_name'] = ['invalid_length'];
        }

        return $errors;
    }

    /** Rails: `exponent` — pricing units always carry two decimals. */
    public function exponent(): int
    {
        return 2;
    }

    /** Rails: `subunit_to_unit` — 10 ** exponent. */
    public function subunitToUnit(): int
    {
        return 10 ** $this->exponent();
    }

    protected function casts(): array
    {
        return [

        ];
    }
}
