<?php

declare(strict_types=1);

namespace App\Models;

use App\Models\Casts\PostgresArray;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Attributes\Table;
use Illuminate\Database\Eloquent\Attributes\Fillable;

/**
 * Frozen-schema model for `roles`. Generated by scripts/gen-models.php;
 * refine relations, enums and domain methods as services are ported.
 */
#[Fillable([
    'organization_id',
    'code',
    'admin',
    'permissions',
    'name',
    'description',
])]
#[Table(name: 'roles')]
class Role extends BaseModel
{
    use SoftDeletes;

    /**
     * Port of `permissions_hash` — the base map for this role's name with the
     * role's explicitly-granted permission keys forced to true.
     *
     * @return array<string, bool>
     */
    public function permissionsHash(): array
    {
        $hash = Permission::permissionsHash($this->name);

        foreach ((array) $this->permissions as $granted) {
            if (array_key_exists($granted, $hash)) {
                $hash[$granted] = true;
            }
        }

        return $hash;
    }

    protected function casts(): array
    {
        return [
            'admin' => 'boolean',
            // Frozen column is varchar[] — the JSON 'array' cast writes a
            // malformed array literal.
            'permissions' => PostgresArray::class,
        ];
    }
}
