<?php

namespace App\Models;

use App\Models\BaseModel;
use App\Models\Casts\BcNumeric;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Frozen-schema model for `roles`. Generated by scripts/gen-models.php;
 * refine relations, enums and domain methods as services are ported.
 */
class Role extends BaseModel
{
    use SoftDeletes;

    protected $table = 'roles';

    protected $fillable = [
        'organization_id',
        'code',
        'admin',
        'permissions',
        'name',
        'description',
    ];

    protected $casts = [
        'admin' => 'boolean',
        'permissions' => 'array',
    ];
}
