<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Frozen-schema model for `roles`. Generated by scripts/gen-models.php;
 * refine relations, enums and domain methods as services are ported.
 */
#[\Illuminate\Database\Eloquent\Attributes\Fillable([
    'organization_id',
    'code',
    'admin',
    'permissions',
    'name',
    'description',
])]
#[\Illuminate\Database\Eloquent\Attributes\Table(name: 'roles')]
class Role extends BaseModel
{
    use SoftDeletes;

    protected function casts(): array
    {
        return [
            'admin' => 'boolean',
            'permissions' => 'array',
        ];
    }
}
