<?php

namespace App\Models;

use App\Models\BaseModel;
use App\Models\Casts\BcNumeric;

/**
 * Frozen-schema model for `subscriptions`. Generated by scripts/gen-models.php;
 * refine relations, enums and domain methods as services are ported.
 */
class Subscription extends BaseModel
{
    protected $table = 'subscriptions';

    protected $fillable = [
        'customer_id',
        'plan_id',
        'status',
        'canceled_at',
        'terminated_at',
        'started_at',
        'previous_subscription_id',
        'name',
        'external_id',
        'billing_time',
        'subscription_at',
        'ending_at',
        'trial_ended_at',
        'organization_id',
        'on_termination_credit_note',
        'on_termination_invoice',
        'payment_method_id',
        'payment_method_type',
        'skip_invoice_custom_sections',
        'progressive_billing_disabled',
        'last_received_event_on',
        'cancelation_reason',
        'incompleted_at',
        'activated_at',
        'billing_entity_id',
        'consolidate_invoice',
        'skip_daily_usage',
        'cancellation_reason',
        'purchase_order_number',
        'billing_anchor_date',
    ];

    protected $casts = [
        'status' => 'integer',
        'canceled_at' => 'datetime',
        'terminated_at' => 'datetime',
        'started_at' => 'datetime',
        'billing_time' => 'integer',
        'subscription_at' => 'datetime',
        'ending_at' => 'datetime',
        'trial_ended_at' => 'datetime',
        'skip_invoice_custom_sections' => 'boolean',
        'progressive_billing_disabled' => 'boolean',
        'last_received_event_on' => 'date:Y-m-d',
        'incompleted_at' => 'datetime',
        'activated_at' => 'datetime',
        'consolidate_invoice' => 'boolean',
        'skip_daily_usage' => 'boolean',
        'billing_anchor_date' => 'date:Y-m-d',
    ];
}
