<?php

namespace App\Models;

use App\Models\BaseModel;
use App\Models\Casts\BcNumeric;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Frozen-schema model for `taxes`. Generated by scripts/gen-models.php;
 * refine relations, enums and domain methods as services are ported.
 */
class Tax extends BaseModel
{
    use SoftDeletes;

    protected $table = 'taxes';

    protected $fillable = [
        'organization_id',
        'description',
        'code',
        'name',
        'rate',
        'applied_to_organization',
        'auto_generated',
    ];

    protected $casts = [
        'rate' => 'float',
        'applied_to_organization' => 'boolean',
        'auto_generated' => 'boolean',
    ];
}
