<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Support\Collection;
use Illuminate\Database\Eloquent\Attributes\Scope;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Models\Concerns\BelongsToOrganization;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

/**
 * Frozen-schema model for `taxes`. Generated by scripts/gen-models.php;
 * refined with the Rails Tax model's relations, scopes, domain methods and
 * validations.
 */
#[\Illuminate\Database\Eloquent\Attributes\Fillable([
    'organization_id',
    'description',
    'code',
    'name',
    'rate',
    'applied_to_organization',
    'auto_generated',
])]
#[\Illuminate\Database\Eloquent\Attributes\Table(name: 'taxes')]
class Tax extends BaseModel
{
    use BelongsToOrganization;
    use HasFactory;
    use SoftDeletes;

    /** Rails: ORDERS. */
    public const ORDERS = ['name', 'rate'];

    /**
     * Rails' ActiveRecord carries the schema's column defaults in every new
     * instance; Eloquent does not, so the NOT NULL DEFAULT columns are
     * declared here to keep reads (and the serializers) identical to Rails.
     */
    protected $attributes = [
        'rate' => 0.0,
        'applied_to_organization' => false,
        'auto_generated' => false,
    ];

    // -- Relationships --------------------------------------------------------

    /** Rails: `belongs_to :organization`. */
    public function organization(): BelongsTo
    {
        return $this->belongsTo(Organization::class);
    }

    /** Rails: `has_many :applied_taxes, class_name: "Customer::AppliedTax"` (customers_taxes). */
    public function appliedTaxes(): HasMany
    {
        return $this->hasMany(CustomerTax::class, 'tax_id');
    }

    /** Rails: `has_many :customers, through: :applied_taxes`. */
    public function customers(): BelongsToMany
    {
        return $this->belongsToMany(Customer::class, 'customers_taxes', 'tax_id', 'customer_id')
            ->whereNull('customers.deleted_at');
    }

    // -- Scopes ---------------------------------------------------------------

    /** Rails: `scope :applied_to_organization`. */
    #[Scope]
    protected function appliedToOrganization(Builder $query): Builder
    {
        return $query->where('applied_to_organization', true);
    }

    /**
     * Rails: `scope :applied_to_billing_entity` — taxes attached to the
     * billing entity through the `billing_entities_taxes` join (no model for
     * the join table yet — queried directly).
     */
    #[Scope]
    protected function appliedToBillingEntity(Builder $query, BillingEntity $billingEntity): Builder
    {
        return $query->whereIn('id', static::billingEntitiesTaxes()
            ->where('billing_entity_id', $billingEntity->id)
            ->select('tax_id'));
    }

    // -- Domain methods (ports of the Rails instance methods) ------------------

    /**
     * Rails: `billing_entities` (through :billing_entities_taxes) — no
     * BillingEntityAppliedTax model exists yet, so the join table is queried
     * directly; returns the kept billing entities.
     *
     * @return Collection<int, BillingEntity>
     */
    public function billingEntities(): Collection
    {
        $ids = static::billingEntitiesTaxes()
            ->where('tax_id', $this->id)
            ->pluck('billing_entity_id')
            ->all();

        if ($ids === []) {
            return collect();
        }

        return BillingEntity::query()->whereIn('id', $ids)->get();
    }

    /**
     * Rails: `customers_count` — the count of applicable customers.
     */
    public function customersCount(): int
    {
        return $this->applicableCustomers()->count();
    }

    /**
     * Rails: `applicable_customers` — returns the customers query:
     *
     * - the attached customers when the tax is not applied to any billing
     *   entity (tax is attached only to customers);
     * - otherwise, the customers of the billing entities carrying this tax
     *   that have no applied tax (the tax is their default) plus the
     *   customers attached to the current tax.
     */
    public function applicableCustomers(): Builder
    {
        $billingEntityIds = static::billingEntitiesTaxes()
            ->where('tax_id', $this->id)
            ->pluck('billing_entity_id')
            ->all();

        if ($billingEntityIds === []) {
            return Customer::query()->whereIn('customers.id', $this->customers()->select('customers.id'));
        }

        $customersWithoutTaxes = Customer::query()
            ->leftJoin('customers_taxes', 'customers_taxes.customer_id', '=', 'customers.id')
            ->where('customers.organization_id', $this->organization_id)
            ->whereIn('customers.billing_entity_id', $billingEntityIds)
            ->groupBy('customers.id')
            ->havingRaw('COUNT(customers_taxes.id) = 0')
            ->select('customers.id');

        $attached = $this->customers()->select('customers.id');

        return Customer::query()->where(function (Builder $query) use ($customersWithoutTaxes, $attached): void {
            $query
                ->whereIn('customers.id', $customersWithoutTaxes)
                ->orWhereIn('customers.id', $attached);
        });
    }

    // -- Validations ------------------------------------------------------------

    /**
     * Port of the Rails model validations — `field => [api error codes]`,
     * empty when valid.
     *
     * @return array<string, list<string>>
     */
    public function validateAttributes(): array
    {
        $errors = [];

        if (($this->name ?? '') === '') {
            $errors['name'] = ['value_is_mandatory'];
        }

        if ($this->rate === null) {
            $errors['rate'] = ['value_is_mandatory'];
        }

        if (($this->code ?? '') === '') {
            $errors['code'] = ['value_is_mandatory'];
        } else {
            $uniqueness = static::query()
                ->where('code', $this->code)
                ->where('organization_id', $this->organization_id)
                ->whereNull('deleted_at');

            if ($this->exists) {
                $uniqueness->where($this->getKeyName(), '!=', $this->getKey());
            }

            if ($uniqueness->exists()) {
                $errors['code'] = ['value_already_exist'];
            }
        }

        return $errors;
    }

    /** Query builder over the `billing_entities_taxes` join table. */
    protected static function billingEntitiesTaxes(): \Illuminate\Database\Query\Builder
    {
        return \Illuminate\Support\Facades\DB::table('billing_entities_taxes');
    }
}
