<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Frozen-schema model for `taxes`. Generated by scripts/gen-models.php;
 * refine relations, enums and domain methods as services are ported.
 */
#[\Illuminate\Database\Eloquent\Attributes\Fillable([
    'organization_id',
    'description',
    'code',
    'name',
    'rate',
    'applied_to_organization',
    'auto_generated',
])]
#[\Illuminate\Database\Eloquent\Attributes\Table(name: 'taxes')]
class Tax extends BaseModel
{
    use SoftDeletes;
    protected function casts(): array
    {
        return [
            'rate' => 'float',
            'applied_to_organization' => 'boolean',
            'auto_generated' => 'boolean',
        ];
    }
}
