<?php

declare(strict_types=1);

namespace App\Models;

/**
 * Frozen-schema model for `webhooks`. Generated by scripts/gen-models.php;
 * refine relations, enums and domain methods as services are ported.
 */
#[\Illuminate\Database\Eloquent\Attributes\Fillable([
    'object_id',
    'object_type',
    'status',
    'retries',
    'http_status',
    'endpoint',
    'webhook_type',
    'payload',
    'response',
    'last_retried_at',
    'webhook_endpoint_id',
    'organization_id',
    'payload_key',
    'response_key',
])]
#[\Illuminate\Database\Eloquent\Attributes\Table(name: 'webhooks')]
class Webhook extends BaseModel
{
    protected function casts(): array
    {
        return [
            'status' => 'integer',
            'retries' => 'integer',
            'http_status' => 'integer',
            'payload' => 'array',
            'response' => 'array',
            'last_retried_at' => 'datetime',
        ];
    }
}
