<?php

declare(strict_types=1);

namespace App\Models;

/**
 * Frozen-schema model for `webhook_endpoints`. Generated by scripts/gen-models.php;
 * refine relations, enums and domain methods as services are ported.
 */
#[\Illuminate\Database\Eloquent\Attributes\Fillable([
    'organization_id',
    'webhook_url',
    'signature_algo',
    'event_types',
    'name',
])]
#[\Illuminate\Database\Eloquent\Attributes\Table(name: 'webhook_endpoints')]
class WebhookEndpoint extends BaseModel
{
    protected function casts(): array
    {
        return [
            'signature_algo' => 'integer',
            'event_types' => 'array',
        ];
    }
}
