<?php

namespace App\Models;

use App\Models\BaseModel;
use App\Models\Casts\BcNumeric;

/**
 * Frozen-schema model for `webhooks`. Generated by scripts/gen-models.php;
 * refine relations, enums and domain methods as services are ported.
 */
class Webhook extends BaseModel
{
    protected $table = 'webhooks';

    protected $fillable = [
        'object_id',
        'object_type',
        'status',
        'retries',
        'http_status',
        'endpoint',
        'webhook_type',
        'payload',
        'response',
        'last_retried_at',
        'webhook_endpoint_id',
        'organization_id',
        'payload_key',
        'response_key',
    ];

    protected $casts = [
        'status' => 'integer',
        'retries' => 'integer',
        'http_status' => 'integer',
        'payload' => 'array',
        'response' => 'array',
        'last_retried_at' => 'datetime',
    ];
}
