<?php

namespace App\Models;

use App\Models\BaseModel;
use App\Models\Casts\BcNumeric;

/**
 * Frozen-schema model for `webhook_endpoints`. Generated by scripts/gen-models.php;
 * refine relations, enums and domain methods as services are ported.
 */
class WebhookEndpoint extends BaseModel
{
    protected $table = 'webhook_endpoints';

    protected $fillable = [
        'organization_id',
        'webhook_url',
        'signature_algo',
        'event_types',
        'name',
    ];

    protected $casts = [
        'signature_algo' => 'integer',
        'event_types' => 'array',
    ];
}
